#ifndef __BOOTX64_H__
#define __BOOTX64_H__

#include <stdint.h>

//二章三部一節に記載せらるデータ型の定義
//余分な<Enumerated Type>及びsizeof(VOID *)(コンパイラに依りサイズは規定される)、Bitfields(AIに拠れば抑々非推奨と云う)は定義しない
//<Enumerated Type>(ANSI C内のenum)はサイズが不安定な為、構造体内で使用しない様にすべきだが、関数引数としての利用は許容される
typedef unsigned char BOOLEAN;
typedef intptr_t INTN;
typedef uintptr_t UINTN;
typedef char INT8;
typedef unsigned char UINT8;
typedef short int INT16;
typedef unsigned short int UINT16;
typedef long int INT32;
typedef unsigned long int UINT32;
typedef long long int INT64;
typedef unsigned long long int UINT64;
typedef struct{ intptr_t high; intptr_t low ; }INT128; //計算や比較演算は不可能
typedef struct{ uintptr_t high; uintptr_t low ; }UINT128; //上記と同じ
typedef char CHAR8;
typedef short CHAR16;
typedef void VOID;
typedef struct{ UINT32 Data1; UINT16 Data2; UINT16 Data3; UINT8 Data4[8]; }EFI_GUID;
typedef UINTN EFI_STATUS;
typedef VOID *EFI_HANDLE;
typedef VOID *EFI_EVENT;
typedef UINT64 EFI_LBA;
typedef UINTN EFI_TPL;
typedef struct{ UINT8 Addr[32]; }EFI_MAC_ADDRESS;
typedef struct{ UINT8 Addr[4]; }EFI_IPv4_ADDRESS;
typedef struct{ UINT8 Addr[16]; }EFI_IPv6_ADDRESS;
typedef struct{ UINT32 Addr[4]; EFI_IPv4_ADDRESS v4; EFI_IPv6_ADDRESS v6;}EFI_IP_ADDRESS;

//上記と同じ章に記載せらるニーモニックの定義・読解上の手助けであり、特に意味は無い
#define IN
#define OUT
#define OPTIONAL
#define CONST
#define EFIAPI

//四章一部一節に記載せらるEFI_IMAGE_ENTRY_POINTの定義
typedef EFI_SYSTEM_TABLE EFI_SYSTEM_TABLE;
typedef EFI_STATUS (EFIAPI *EFI_IMAGE_ENTRY_POINT) (IN EFI_HANDLE ImageHandle, IN EFI_SYSTEM_TABLE *SystemTable);
#define EFI_SUCCESS

//四章二部一節に記載せらるEFI_TABLE_HEADERの定義
typedef struct { UINT64 Signature; UINT32 Revision; UINT32 HeaderSize; UINT32 CRC32; UINT32 Reserved; }EFI_TABLE_HEADER;

//四章三部一節に記載せらるEFI_SYSTEM_TABLEの定義
#define EFI_SYSTEM_TABLE_SIGNATURE 0x5453595320494249
#define EFI_2_100_SYSTEM_TABLE_REVISION ((2<<16) | (100))
#define EFI_2_90_SYSTEM_TABLE_REVISION ((2<<16) | (90))
#define EFI_2_80_SYSTEM_TABLE_REVISION ((2<<16) | (80))
#define EFI_2_70_SYSTEM_TABLE_REVISION ((2<<16) | (70))
#define EFI_2_60_SYSTEM_TABLE_REVISION ((2<<16) | (60))
#define EFI_2_50_SYSTEM_TABLE_REVISION ((2<<16) | (50))
#define EFI_2_40_SYSTEM_TABLE_REVISION ((2<<16) | (40))
#define EFI_2_30_SYSTEM_TABLE_REVISION ((2<<16) | (30))
#define EFI_2_20_SYSTEM_TABLE_REVISION ((2<<16) | (20))
#define EFI_2_10_SYSTEM_TABLE_REVISION ((2<<16) | (10))
#define EFI_2_00_SYSTEM_TABLE_REVISION ((2<<16) | (00))
#define EFI_1_10_SYSTEM_TABLE_REVISION ((1<<16) | (10))
#define EFI_1_02_SYSTEM_TABLE_REVISION ((1<<16) | (02))
#define EFI_SPECIFICATION_VERSION EFI_SYSTEM_TABLE_REVISION
#define EFI_SYSTEM_TABLE_REVISION EFI_2_100_SYSTEM_TABLE_REVISION

typedef EFI_SIMPLE_TEXT_INPUT_PROTOCOL EFI_SIMPLE_TEXT_INPUT_PROTOCOL;
typedef EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL;
typedef EFI_RUNTIME_SERVICES EFI_RUNTIME_SERVICES;
typedef EFI_BOOT_SERVICES EFI_BOOT_SERVICES;
typedef EFI_CONFIGURATION_TABLE EFI_CONFIGURATION_TABLE;
typedef struct { EFI_TABLE_HEADER Hdr; CHAR16 *FirmwareVendor; UINT32 FirmwareRevision; EFI_HANDLE ConsoleInHandle; EFI_SIMPLE_TEXT_INPUT_PROTOCOL *ConIn; EFI_HANDLE ConsoleOutHandle; EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *ConOut; EFI_HANDLE StandardErrorHandle; EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *StdErr; EFI_RUNTIME_SERVICES *RuntimeServices; EFI_BOOT_SERVICES *BootServices; UINTN NumberOfTableEntries; EFI_CONFIGURATION_TABLE *ConfigurationTable; }EFI_SYSTEM_TABLE;

//四章四部一節に記載せらるEFI_BOOT_SERVICESの定義
#define EFI_BOOT_SERVICES_SIGNATURE 0x56524553544f4f42
#define EFI_BOOT_SERVICES EFI_SPECIFICATION_VERSION

typedef EFI_RAISE_TPL EFI_RAISE_TPL;
typedef EFI_RESTORE_TPL EFI_RESTORE_TPL;
typedef EFI_ALLOCATE_PAGES EFI_ALLOCATE_PAGES;
typedef EFI_FREE_PAGES EFI_FREE_PAGES;
typedef EFI_GET_MEMORY_MAP EFI_GET_MEMORY_MAP;
typedef EFI_ALLOCATE_POOL EFI_ALLOCATE_POOL;
typedef EFI_FREE_POOL EFI_FREE_POOL;
typedef EFI_CREATE_EVENT EFI_CREATE_EVENT;
typedef EFI_SET_TIMER EFI_SET_TIMER;
typedef EFI_WAIT_FOR_EVENT EFI_WAIT_FOR_EVENT;
typedef EFI_SIGNAL_EVENT EFI_SIGNAL_EVENT;
typedef EFI_CLOSE_EVENT EFI_CLOSE_EVENT;
typedef EFI_CHECK_EVENT EFI_CHECK_EVENT;
typedef EFI_INSTALL_PROTOCOL_INTERFACE EFI_INSTALL_PROTOCOL_INTERFACE;
typedef EFI_REINSTALL_PROTOCOL_INTERFACE EFI_REINSTALL_PROTOCOL_INTERFACE;
typedef EFI_UNINSTALL_PROTOCOL_INTERFACE EFI_UNINSTALL_PROTOCOL_INTERFACE;
typedef EFI_HANDLE_PROTOCOL EFI_HANDLE_PROTOCOL;
typedef EFI_REGISTER_PROTOCOL_NOTIFY EFI_REGISTER_PROTOCOL_NOTIFY;
typedef EFI_LOCATE_HANDLE EFI_LOCATE_HANDLE;
typedef EFI_INSTALL_CONFIGURATION_TABLE EFI_INSTALL_CONFIGURATION_TABLE;
typedef EFI_LOCATE_DEVICE_PATH EFI_LOCATE_DEVICE_PATH;
typedef EFI_IMAGE_UNLOAD EFI_IMAGE_UNLOAD;
typedef EFI_IMAGE_START EFI_IMAGE_START;
typedef EFI_EXIT EFI_EXIT;
typedef EFI_EXIT_BOOT_SERVICES EFI_EXIT_BOOT_SERVICES;
typedef EFI_GET_NEXT_MONOTONIC_COUNT EFI_GET_NEXT_MONOTONIC_COUNT;
typedef EFI_STALL EFI_STALL;
typedef EFI_SET_WATCH_TIMER EFI_SET_WATCH_TIMER;
typedef EFI_CONNECT_CONTROLLER EFI_CONNECT_CONTROLLER;
typedef EFI_DISCONNECT_CONTROLLER EFI_DISCONNECT_CONTROLLER;
typedef EFI_OPEN_PROTOCOL EFI_OPEN_PROTOCOL;
typedef EFI_CLOSE_PROTOCOL EFI_CLOSE_PROTOCOL;
typedef EFI_OPEN_PROTOCOL_INFORMATION EFI_OPEN_PROTOCOL_INFORMATION;
typedef EFI_PROTOCOLS_PER_HANDLE EFI_PROTOCOLS_PER_HANDLE;
typedef EFI_LOCATE_HANDLE_BUFFER EFI_LOCATE_HANDLE_BUFFER;
typedef EFI_LOCATE_PROTOCOL EFI_LOCATE_PROTOCOL;
typedef EFI_UNINSTALL_MULTIPLE_PROTOCOL_INTERFACES EFI_UNINSTALL_MULTIPLE_PROTOCOL_INTERFACES;
typedef EFI_CALCULATE_CRC32 EFI_CALCULATE_CRC32;
typedef EFI_COPY_MEM EFI_COPY_MEM;
typedef EFI_SET_MEM EFI_SET_MEM;
typedef EFI_CREATE_EVENT_EX EFI_CREATE_EVENT_EX;
typedef struct { EFI_TABLE_HEADER Hdr; EFI_RAISE_TPL RaiseTPL; EFI_RESTORE_TPL RestoreTPL; EFI_ALLOCATE_PAGES AllocatePages; EFI_FREE_PAGES FreePages; EFI_GET_MEMORY_MAP GetMemoryMap; EFI_ALLOCATE_POOL AllocatePool; EFI_FREE_POOL FreePool; EFI_CREATE_EVENT CreateEvent; EFI_SET_TIMER SetTimer; EFI_WAIT_FOR_EVENT WaitForEvent; EFI_SIGNAL_EVENT SignalEvent; EFI_CLOSE_EVENT CloseEvent; EFI_CHECK_EVENT CheckEvent; EFI_INSTALL_PROTOCOL_INTERFACE InstallProtocolInterface; EFI_REINSTALL_PROTOCOL_INTERFACE ReinstallProtocolInterface; EFI_UNINSTALL_PROTOCOL_INTERFACE UninstallProtocolInterface; EFI_HANDLE_PROTOCOL HandleProtocol; VOID* Reserved; EFI_REGISTER_PROTOCOL_NOTIFY RegisterProtocolNotify; EFI_LOCATE_HANDLE LocateHandle; EFI_LOCATE_DEVICE_PATH LocateDevicePath; EFI_INSTALL_CONFIGURATION_TABLE InstallConfigurationTable; EFI_IMAGE_UNLOAD LoadImage; EFI_IMAGE_START StartImage; EFI_EXIT Exit; EFI_IMAGE_UNLOAD UnloadImage; EFI_EXIT_BOOT_SERVICES ExitBootServices; EFI_GET_NEXT_MONOTONIC_COUNT GetNextMonotonicCount; EFI_STALL stall; EFI_SET_WATCH_TIMER SetWatchdogTimer; EFI_CONNECT_CONTROLLER ConnectController; EFI_DISCONNECT_CONTROLLER DisconnectController; EFI_OPEN_PROTOCOL OpenProtocol; EFI_CLOSE_PROTOCOL CloseProtocol; EFI_OPEN_PROTOCOL_INFORMATION OpenProtocolInformation; EFI_PROTOCOLS_PER_HANDLE ProtocolsPerHandle; EFI_LOCATE_HANDLE_BUFFER LocateHandleBuffer; EFI_LOCATE_PROTOCOL LocateProtocol; EFI_UNINSTALL_MULTIPLE_PROTOCOL_INTERFACES InstallMultipleProtocolInterfaces; EFI_UNINSTALL_MULTIPLE_PROTOCOL_INTERFACES UninstallMultipleProtocolInterfaces; EFI_CALCULATE_CRC32 CalculateCrc32; EFI_COPY_MEM CopyMem; EFI_SET_MEM SetMem; EFI_CREATE_EVENT_EX CreateEventEx;}EFI_BOOT_SERVICE;

//四章五部一節に記載せらるEFI_RUNTIME_SERVICESの定義
typedef EFI_GET_TIME EFI_GET_TIME;
typedef EFI_SET_TIME EFI_SET_TIME;
typedef EFI_GET_WAKEUP_TIME EFI_GET_WAKEUP_TIME;
typedef EFI_SET_WAKEUP_TIME EFI_SET_WAKEUP_TIME;
typedef EFI_SET_VIRTUAL_ADDRESS_MAP EFI_SET_VIRTUAL_ADDRESS_MAP;
typedef EFI_CONVERT_POINTER EFI_CONVERT_POINTER;
typedef EFI_GET_VARIABLE EFI_GET_VARIABLE;
typedef EFI_GET_NEXT_VARIABLE_NAME EFI_GET_NEXT_VARIABLE_NAME;
typedef EFI_SET_VARIABLE EFI_SET_VARIABLE;
typedef EFI_GET_NEXT_HIGH_MONO_COUNT EFI_GET_NEXT_HIGH_MONO_COUNT;
typedef EFI_RESET_SYSTEM EFI_RESET_SYSTEM;
typedef EFI_UPDATE_CAPSULE EFI_UPDATE_CAPSULE;
typedef EFI_QUERY_CAPSULE_CAPABILITIES EFI_QUERY_CAPSULE_CAPABILITIES;
typedef EFI_QUERY_VARIABLE_INFO EFI_QUERY_VARIABLE_INFO;
typedef struct { EFI_TABLE_HEADER Hdr; EFI_GET_TIME GetTime; EFI_SET_TIME SetTime; EFI_GET_WAKEUP_TIME GetWakeupTime; EFI_SET_WAKEUP_TIME SetWakeupTime; EFI_SET_VIRTUAL_ADDRESS_MAP SetVirtualAddressMap; EFI_CONVERT_POINTER ConvertPointer; EFI_GET_VARIABLE GetVariable; EFI_GET_NEXT_VARIABLE_NAME GetNextVariableName; EFI_SET_VARIABLE SetVariable; EFI_GET_NEXT_HIGH_MONO_COUNT GetNextHighMonotonicCount; EFI_RESET_SYSTEM ResetSystem; EFI_UPDATE_CAPSULE UpdateCapsule; EFI_QUERY_CAPSULE_CAPABILITIES QueryCapsuleCapabilities; EFI_QUERY_VARIABLE_INFO QueryVariableInfo; }EFI_RUNTIME_SERVICES;

//四章六部一節に記載せらるEFI_CONFIGURATION_TABLEの定義
typedef struct{ EFI_GUID VendorGuid; VOID *VendorTable; }EFI_CONFIGURATION_TABLE;

//四章六部一節一に記載せらるIndustry Standard Configuration Tablesの定義
#define EFI_ACPI_20_TABLE_GUID {0x8868e871,0xe4f1,0x11d3,{0xbc,0x22,0x00,0x80,0xc7,0x3c,0x88,0x81}}
#define ACPI_TABLE_GUID {0xeb9d2d30,0x2d88,0x11d3,{0x9a,0x16,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
#define SAL_SYSTEM_TABLE_GUID {0xeb9d2d32,0x2d88,0x11d3,{0x9a,0x16,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
#define SMBIOS_TABLE_GUID {0xeb9d2d31,0x2d88,0x11d3,{0x9a,0x16,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
#define SMBIOS3_TABLE_GUID {0xf2fd1544,0x9794,0x4a2c,{0x99,0x2e,0xe5,0xbb,0xcf,0x20,0xe3,0x94}}
#define MPS_TABLE_GUID {0xeb9d2d2f,0x2d88,0x11d3,{0x9a,0x16,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
#define EFI_ACPI_TABLE_GUID {0x8868e871,0xe4f1,0x11d3,{0xbc,0x22,0x00,0x80,0xc7,0x3c,0x88,0x81}}
#define EFI_ACPI_20_TABLE_GUID EFI_ACPI_TABLE_GUID
#define ACPI_TABLE_GUID {0xeb9d2d30,0x2d88,0x11d3,{0x9a,0x16,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
#define ACPI_10_TABLE_GUID ACPI_TABLE_GUID*

//四章六部一節二に記載せらるJSON Configuration Tablesの定義
#define EFI_JSON_CONFIG_DATA_TABLE_GUID {0x87367f87,0x1119,0x41ce,{0xaa,0xec,0x8b,0xe0,0x11,0x1f,0x55,0x8a}}
#define EFI_JSON_CAPSULE_DATA_TABLE_GUID {0x35e7a725,0x8dd2,0x4cac,{0x80,0x11,0x33,0xcd,0xa8,0x10,0x90,0x56}}
#define EFI_JSON_CAPSULE_RESULT_TABLE_GUID {0xdbc461c3,0xb3de,0x422a,{0xb9,0xb4,0x98,0x86,0xfd,0x49,0xa1,0xe5}}

//四章六部一節三に記載せらるDevicetree Tablesの定義
#define EFI_DTB_TABLE_GUID {0xb1b621d5,0xf19c,0x41a5,{0x83,0x0b,0xd9,0x15,0x2c,0x69,0xaa,0xe0}}

//四章六部二節に記載せらるEFI_RT_PROPERTIES_TABLEの定義
#define EFI_RT_PROPERTIES_TABLE_GUID{0xeb66918a,0x7eef,0x402a,{0x84,0x2e,0x93,0x1d,0x21,0xc3,0x8a,0xe9}}
typedef struct { UINT16 Version; UINT16 Length; UINT32 RuntimeServicesSupported;}EFI_RT_PROPERTIES_TABLE;
#define EFI_RT_PROPERTIES_TABLE_VERSION 0x1
#define EFI_RT_SUPPORTED_GET_TIME 0x0001
#define EFI_RT_SUPPORTED_SET_TIME 0x0002
#define EFI_RT_SUPPORTED_GET_WAKEUP_TIME 0x0004
#define EFI_RT_SUPPORTED_SET_WAKEUP_TIME 0x0008
#define EFI_RT_SUPPORTED_GET_VARIABLE 0x0010
#define EFI_RT_SUPPORTED_GET_NEXT_VARIABLE_NAME 0x0020
#define EFI_RT_SUPPORTED_SET_VARIABLE 0x0040
#define EFI_RT_SUPPORTED_SET_VIRTUAL_ADDRESS_MAP 0x0080
#define EFI_RT_SUPPORTED_CONVERT_POINTER 0x0100
#define EFI_RT_SUPPORTED_GET_NEXT_HIGH_MONOTONIC_COUNT 0x0200
#define EFI_RT_SUPPORTED_RESET_SYSTEM 0x0400
#define EFI_RT_SUPPORTED_UPDATE_CAPSULE 0x0800
#define EFI_RT_SUPPORTED_QUERY_CAPSULE_CAPABILITIES 0x1000
#define EFI_RT_SUPPORTED_QUERY_VARIABLE_INFO 0x2000

//四章六部三節に記載せらるEFI_MEMORY_ATTRIBUTES_TABLEの定義
#define EFI_MEMORY_ATTRIBUTES_TABLE_GUID {0xdcfa911d,0x26eb,0x469f,{0xa2,0x20,0x38,0xb7,0xdc,0x46,0x12,0x20}}
typedef EFI_MEMORY_DESCRIPTOR EFI_MEMORY_DESCRIPTOR;
typedef struct { UINT32 Version; UINT32 NumberOfEntries; UINT32 DescriptorSize; UINT32 Flags; EFI_MEMORY_DESCRIPTOR Entry[1]; }EFI_MEMORY_ATTRIBUTES_TABLE;
#define EFI_MEMORY_ATTRIBUTES_FLAGS_RT_FORWARD_CONTROL_FLOW_GUARD 0x1

//四章六部四節に記載せらるEFI_CONFORMANCE_PROFILE_TABLEの定義
#define EFI_CONFORMANCE_PROFILES_TABLE_GUID {0x36122546,0xf7e7,0x4c8f,{0xbd,0x9b,0xeb,0x85,0x25,0xb5,0x0c,0x0b}}
typedef struct { UINT16 Version; UINT16 NumberOfProfiles; EFI_GUID ConformanceProfiles []; }EFI_CONFORMANCE_PROFILES_TABLE;
#define EFI_CONFORMANCE_PROFILES_UEFI_SPEC_GUID {0x523c91af,0xa195,0x4382,{0x81,0x8d,0x29,0x5f,0xe4,0x00,0x64,0x65}}

//四章六部五節に記載せらるOther Configuration Tableの定義
//各章に記載されている為、各章にて取り扱う

//七章一部一節に記載せらるEFI_BOOT_SERVICE.CreateEvent()の定義
typedef EFI_EVENT_NOTIFY EFI_EVENT_NOTIFY;
typedef EFI_STATUS (EFIAPI *EFI_CREATE_EVENT) ( IN UINT32 Type, IN EFI_TPL NotifyTpl, IN EFI_EVENT_NOTIFY NotifyFunction,OPTIONAL IN VOID *NotifyContext,OPTIONAL OUT EFI_EVENT *Event);
typedef VOID *EFI_EVENT;
#define EVT_TIMER 0x80000000
#define EVT_RUNTIME 0x40000000
#define EVT_NOTIFY_WAIT 0x00000100
#define EVT_NOTIFY_SIGNAL 0x00000200
#define EVT_SIGNAL_EXIT_BOOT_SERVICES 0x00000201
#define EVT_SIGNAL_VIRTUAL_ADDRESS_CHANGE 0x60000202
typedef VOID (EFIAPI *EFI_EVENT_NOTIFY) (IN EFI_EVENT Event, IN VOID *Context);

//七章一部二節に記載せらるEFI_BOOT_SERVICES.CreateEventEx()の定義
typedef EFI_STATUS (EFIAPI *EFI_CREATE_EVENT_EX) (IN UINT32 Type, IN EFI_TPL NotifyTpl, IN EFI_EVENT_NOTIFY NotifyFunction OPTIONAL, IN CONST VOID *NotifyContext OPTIONAL, IN CONST EFI_GUID *EventGroup OPTIONAL, OUT EFI_EVENT *Event);
#define EFI_EVENT_GROUP_EXIT_BOOT_SERVICES {0x27abf055,0xb1b8,0x4c26,0x80,0x48,0x74,0x8f,0x37,0xba,0xa2,0xdf}
#define EFI_EVENT_GROUP_BEFORE_EXIT_BOOT_SERVICES {0x8be0e274,0x3970,0x4b44,{0x80,0xc5,0x1a,0xb9,0x50,0x2f,0x3b,0xfc}}
#define EFI_EVENT_GROUP_VIRTUAL_ADDRESS_CHANGE {0x13fa7698,0xc831,0x49c7,0x87,0xea,0x8f,0x43,0xfc,0xc2,0x51,0x96}
#define EFI_EVENT_GROUP_MEMORY_MAP_CHANGE {0x78bee926,0x692f,0x48fd,0x9e,0xdb,0x1,0x42,0x2e,0xf0,0xd7,0xab}
#define EFI_EVENT_GROUP_READY_TO_BOOT {0x7ce88fb3,0x4bd7,0x4679,0x87,0xa8,0xa8,0xd8,0xde,0xe5,0xd,0x2b}
#define EFI_EVENT_GROUP_AFTER_READY_TO_BOOT {0x3a2a00ad,0x98b9,0x4cdf,{0xa4,0x78,0x70,0x27,0x77,0xf1,0xc1,0xb}}
#define EFI_EVENT_GROUP_RESET_SYSTEM {0x62da6a56,0x13fb,0x485a,{0xa8,0xda,0xa3,0xdd,0x79,0x12,0xcb,0x6b}}

//七章一部三節に記載せらるEFI_BOOT_SERVICES.CloseEvent()の定義
typedef EFI_STATUS (EFIAPI *EFI_CLOSE_EVENT) (IN EFI_EVENT Event);

//七章一部四節に記載せらるEFI_BOOT_SERVICES.SignalEvent()の定義
typedef EFI_STATUS (EFIAPI *EFI_SIGNAL_EVENT) (IN EFI_EVENT Event);

//七章一部五節に記載せらるEFI_BOOT_SERVICES.WaitForEvent()の定義
typedef EFI_STATUS (EFIAPI *EFI_WAIT_FOR_EVENT) (IN UINTN NumberOfEvents, IN EFI_EVENT *Event, OUT UINTN *Index);

//七章一部六節に記載せらるEFI_BOOT_SERVICES.CheckEvent()の定義
typedef EFI_STATUS (EFIAPI *EFI_CHECK_EVENT) (IN EFI_EVENT Event);

//七章一部七節に記載せらるEFI_BOOT_SERVICES.SetTimer()の定義
typedef EFI_TIMER_DELAY EFI_TIMER_DELAY;
typedef EFI_STATUS (EFIAPI *EFI_SET_TIMER) (IN EFI_EVENT Event, IN EFI_TIMER_DELAY Type, IN UINT64 TriggerTime);
typedef enum{TimerCancel,TimerPeriodic,TimerRelative}EFI_TIMER_DALAY;

//七章一部八節に記載せらるEFI_BOOT_SERVICES.RaiseTPL()の定義
typedef EFI_TPL (EFIAPI *EFI_RAISE_TPL) (IN EFI_TPL NewTpl);
#define TPL_APPLICATION 4
#define TPL_CALLBACK 8
#define TPL_NOTIFY 16
#define TPL_HIGH_LEVEL 31

//七章一部九節に記載せらるEFI_BOOT_SERVICES.RestoreTPL()の定義
typedef VOID (EFIAPI *EFI_RESTORE_TPL) (IN EFI_TPL OldTpl);

//七章二部一節に記載せらるEFI_BOOT_SERVICES.AllocatePages()の定義
typedef enum{AllocateAnyPages,AllocateMaxAddress,AllocateAddress,MaxAllocateType}EFI_ALLOCATE_TYPE;
typedef enum{EfiReservedMemoryType,EfiLoaderCode,EfiLoaderData,EfiBootServicesCode,EfiBootServicesData,EfiRuntimeServicesCode,EfiRuntimeServicesData,EfiConventionalMemory,EfiUnusableMemory,EfiACPIReclaimMemory,EfiACPIMemoryNVS,EfiMemoryMappedIO,EfiMemoryMappedIOPortSpace,EfiPalCode,EfiPersistentMemory,EfiUnacceptedMemoryType,EfiMaxMemoryType}EFI_MEMORY_TYPE;
typedef UINT64 EFI_PHYSICAL_ADDRESS;
typedef EFI_STATUS (EFIAPI *EFI_ALLOCATE_PAGES) (IN EFI_ALLOCATE_TYPE Type, IN EFI_MEMORY_TYPE MemoryType, IN UINTN Pages, IN OUT EFI_PHYSICAL_ADDRESS *Memory);

//七章二部二節に記載せらるEFI_BOOT_SERVICES.FreePages()の定義
typedef EFI_STATUS (EFIAPI *EFI_FREE_PAGES) (IN EFI_PHYSICAL_ADDRESS Memory, IN UINTN Pages);

//七章二部三節に記載せらるEFI_BOOT_SERVICES.GetMemoryMap()の定義
typedef EFI_STATUS (EFIAPI *EFI_GET_MEMORY_MAP) (IN OUT UINTN *MemoryMapSize, OUT EFI_MEMORY_DESCRIPTOR *MemoryMap, OUT UINTN *MapKey, OUT UINTN *DescriptorSize, OUT UINT32 *DescriptorVersion);
typedef UINT64 EFI_VIRTUAL_ADDRESS;
typedef struct { UINT32 Type; EFI_PHYSICAL_ADDRESS PhysicalStart; EFI_VIRTUAL_ADDRESS VirtualStart; UINT64 NumberOfPages; UINT64 Attribute; }EFI_MEMORY_DESCRIPTOR;
#define EFI_MEMORY_UC 0x0000000000000001
#define EFI_MEMORY_WC 0x0000000000000002
#define EFI_MEMORY_WT 0x0000000000000004
#define EFI_MEMORY_WB 0x0000000000000008
#define EFI_MEMORY_UCE 0x0000000000000010
#define EFI_MEMORY_WP 0x0000000000001000
#define EFI_MEMORY_RP 0x0000000000002000
#define EFI_MEMORY_XP 0x0000000000004000
#define EFI_MEMORY_NV 0x0000000000008000
#define EFI_MEMORY_MORE_RELIABLE 0x0000000000010000
#define EFI_MEMORY_RO 0x0000000000020000
#define EFI_MEMORY_SP 0x0000000000040000
#define EFI_MEMORY_CPU_CRYPTO 0x0000000000080000
#define EFI_MEMORY_HOT_PLUGGABLE 0x0000000000100000
#define EFI_MEMORY_RUNTIME 0x8000000000000000
#define EFI_MEMORY_ISA_VALID 0x4000000000000000
#define EFI_MEMORY_ISA_MASK 0x0FFFF00000000000

//七章二部四節に記載せらるEFI_BOOT_SERVICES.AllocatePool()の定義
typedef EFI_STATUS (EFIAPI *EFI_ALLOCATE_POOL) (IN EFI_MEMORY_TYPE PoolType,IN UINTN Size, OUT VOID **Buffer);

//七章二部五節に記載せらるEFI_BOOT_SERVICES.FreePool()の定義
typedef EFI_STATUS (EFIAPI *EFI_FREE_POOL) (IN VOID *Buffer);

//七章三部二節に記載せらるEFI_BOOT_SERVICES.InstallProtocolInterface()の定義
typedef EFI_STATUS (EFIAPI *EFI_INSTALL_PROTOCOL_INTERFACE) (IN OUT EFI_HANDLE *Handle,IN EFI_GUID *Protocol,IN EFI_INTERFACE_TYPE InterfaceType,IN VOID *Interface);
typedef enum{EFI_NATIVE_INTERFACE}EFI_INTERFACE_TYPE;

//七章三部三節に記載せらるEFI_BOOT_SERVICES.UninstallProtocolInterface()の定義
typedef EFI_STATUS (EFIAPI *EFI_UNINSTALL_PROTOCOL_INTERFACE) (IN EFI_HANDLE Handle,IN EFI_GUID *Protocol,IN VOID *Interface);

//七章三部四節に記載せらるEFI_BOOT_SERVICES.ReinstallProtocolInterface()の定義
typedef EFI_STATUS (EFIAPI *EFI_REINSTALL_PROTOCOL_INTERFACE) (IN EFI_HANDLE Handle,IN EFI_GUID *Protocol,IN VOID *OldInterface,IN VOID *NewInterface);

//七章三部五節に記載せらるEFI_BOOT_SERVICES.RegisterProtocolNotigy()の定義
typedef EFI_STATUS (EFIAPI *EFI_REGISTER_PROTOCOL_NOTIFY) (IN EFI_GUID *Protocol,IN EFI_EVENT Event,OUT VOID **Registration);

//七章三部六節に記載せらるEFI_BOOT_SERVICES.LocateHandle()の定義
typedef EFI_LOCATE_SEARCH_TYPE EFI_LOCATE_SEARCH_TYPE;
typedef EFI_STATUS (EFIAPI *EFI_LOCATE_HANDLE) (IN EFI_LOCATE_SEARCH_TYPE SearchType,IN EFI_GUID *Protocol OPTIONAL,IN VOID *SearchKey OPTIONAL,IN OUT UINTN *BufferSize,OUT EFI_HANDLE *Buffer);
typedef enum{AllHandles,ByRegisterNotify,ByProtocol}EFI_LOCATE_SEARCH_TYPE;

//七章三部七節に記載せらるEFI_BOOT_SERVICES.HandleProtocol()の定義
typedef EFI_STATUS (EFIAPI *EFI_HANDLE_PROTOCOL) (IN EFI_HANDLE Handle, IN EFI_GUID *Protocol, OUT VOID **Interface);
//HandleProtocolの定義も、場合によっては行う

//七章三部八節に記載せらるEFI_BOOT_SERVICES.LocateDevicePath()の定義
typedef EFI_DEVICE_PATH_PROTOCOL EFI_DEVICE_PATH_PROTOCOL;//十章に記載有り
typedef EFI_STATUS (EFIAPI *EFI_LOCATE_DEVICE_PATH) (IN EFI_GUID *Protocol,IN OUT EFI_DEVICE_PATH_PROTOCOL **DevicePath,OUT EFI_HANDLE *Device);

//七章三部九節に記載せらるEFI_BOOT_SERVICES.OpenProtocol()の定義
typedef EFI_STATUS (EFIAPI *EFI_OPEN_PROTOCOL) (IN EFI_HANDLE Handle,IN EFI_GUID *Protocol,OUT VOID **Interface OPTIONAL,IN EFI_HANDLE AgentHandle,IN EFI_HANDLE ControllerHandle,IN UINT32 Attributes);
#define EFI_OPEN_PROTOCOL_BY_HANDLE_PROTOCOL   0x00000001
#define EFI_OPEN_PROTOCOL_GET_PROTOCOL         0x00000002
#define EFI_OPEN_PROTOCOL_TEST_PROTOCOL        0x00000004
#define EFI_OPEN_PROTOCOL_BY_CHILD_CONTROLLER  0x00000008
#define EFI_OPEN_PROTOCOL_BY_DRIVER            0x00000010
#define EFI_OPEN_PROTOCOL_EXCLUSIVE            0x00000020

//七章三部十節に記載せらるEFI_BOOT_SERVICES.CloseProtocol()の定義
typedef EFI_STATUS (EFIAPI *EFI_CLOSE_PROTOCOL) (IN EFI_HANDLE Handle,IN EFI_GUID *Protocol,IN EFI_HANDLE AgentHandle,IN EFI_HANDLE ControllerHandle);

//七章三部十一節に記載せらるEFI_BOOT_SERVICES.OpenProtocolInformation()の定義
typedef EFI_OPEN_PROTOCOL_INFORMATION_ENTRY EFI_OPEN_PROTOCOL_INFORMATION_ENTRY;
typedef EFI_STATUS (EFIAPI *EFI_OPEN_PROTOCOL_INFORMATION) (IN EFI_HANDLE Handle,IN EFI_GUID *Protocol,OUT EFI_OPEN_PROTOCOL_INFORMATION_ENTRY **EntryBuffer,OUT UINTN *EntryCount);
typedef struct{ EFI_HANDLE AgentHandle; EFI_HANDLE ControllerHandle; UINT32 Attributes; UINT32 OpenCount; }EFI_OPEN_PROTOCOL_INFORMATION_ENTRY;

//七章三部十二節に記載せらるEFI_BOOT_SERVICES.ConnectController()の定義
typedef EFI_STATUS (EFIAPI *EFI_CONNECT_CONTROLLER) (IN EFI_HANDLE ControllerHandle,IN EFI_HANDLE *DriverImageHandle OPTIONAL,IN EFI_DEVICE_PATH_PROTOCOL *RemainingDevicePath OPTIONAL,IN BOOLEAN Recursive);

//七章三部十三節に記載せらるEFI_BOOT_SERVICES.DisconnectController()の定義
typedef EFI_STATUS (EFIAPI *EFI_DISCONNECT_CONTROLLER) (IN EFI_HANDLE ControllerHandle,IN EFI_HANDLE DriverImageHandle OPTIONAL,IN EFI_HANDLE ChildHandle OPTIONAL);

//七章三部十四節に記載せらるEFI_BOOT_SERVICES.ProtocolPerHandle()の定義
typedef EFI_STATUS (EFIAPI *EFI_PROTOCOLS_PER_HANDLE) (IN EFI_HANDLE Handle,OUT EFI_GUID ***ProtocolBuffer,OUT UINTN *ProtocolBufferCount);

//七章三部十五節に記載せらるEFI_BOOT_SERVICES.LocateHandleBuffer()の定義
typedef EFI_STATUS (EFIAPI *EFI_LOCATE_HANDLE_BUFFER) (IN EFI_LOCATE_SEARCH_TYPE SearchType,IN EFI_GUID *Protocol OPTIONAL,IN VOID *SeachKey OPTIONAL, OUT UINTN *NoHandles,OUT EFI_HANDLE **Buffer);

//七章三部十六節に記載せらるEFI_BOOT_SERVICES.LocateProtocol()の定義
typedef EFI_STATUS (EFIAPI *EFI_LOCATE_PROTOCOL) (IN EFI_GUID *Protocol,IN VOID *Registration OPTIONAL,OUT VOID **Interface);

//七章三部十七節に記載せらるEFI_BOOT_SERVICES.InstallMultipleProtocolInterfaces()の定義
typedef EFI_STATUS (EFIAPI *EFI_INSTALL_MULTIPLE_PROTOCOL_INTERFACES) (IN OUT EFI_HANDLE *Handle,...);

//七章三部十八節に記載せらるEFI_BOOT_SERVICES.UninstallMultipleProtocolInterfaces()の定義
typedef EFI_STATUS (EFIAPI *EFI_UNINSTALL_MULTIPLE_PROTOCOL_INTERFACES) (IN EFI_HANDLE Handle,...);

//七章四部一節に記載せらるEFI_BOOT_SERVICES.LoadImage()の定義
typedef EFI_STATUS (EFIAPI *EFI_IMAGE_LOAD)(IN BOOLEAN BootPolicy,IN EFI_HANDLE ParentImageHandle,IN EFI_DEVICE_PATH_PROTOCOL *DevicePath OPTIONAL,IN VOID *SourceBuffer OPTIONAL,IN UINTN SourceSize,OUT EFI_HANDLE *ImageHandle);

//七章四部二節に記載せらるEFI_BOOT_SERVICES.StartImage()の定義
typedef EFI_STATUS (EFIAPI *EFI_IMAGE_START)(IN EFI_HANDLE ImageHandle,OUT UINTN *ExitDataSize,OUT CHAR16 **ExitData OPTIONAL);

//七章四部三節に記載せらるEFI_BOOT_SERVICES.UnloadImage()の定義
typedef EFI_STATUS (EFIAPI *EFI_IMAGE_UNLOAD)(IN EFI_HANDLE ImageHandle);

//七章四部四節に記載せらるEFI_IMAGE_ENTRY_POINTの定義
typedef EFI_STATUS (EFIAPI *EFI_IMAGE_ENTRY_POINT)(IN EFI_HANDLE ImageHandle,IN EFI_SYSTEM_TABLE *SystemTable);

//七章四部五節に記載せらるEFI_BOOT_SERVICES.Exit()の定義
typedef EFI_STATUS (EFIAPI *EFI_EXIT)(IN EFI_HANDLE ImageHandle,IN EFI_STATUS ExitStatus,IN UINTN ExitDataSize,IN CHAR16 *ExitData OPTIONAL);

//七章四部六節に記載せらるEFI_BOOT_SERVICES.ExitBootServices()の定義
typedef EFI_STATUS (EFIAPI *EFI_EXIT_BOOT_SERVICES)(IN EFI_HANDLE ImageHandle, IN UINTN MapKey);

//七章五部一節に記載せらるEFI_BOOT_SERVICES.SetWatchdogTimer()の定義
typedef EFI_STATUS (EFIAPI *EFI_SET_WATCHDOG_TIMER)(IN UINTN Timeout,IN UINT64 WatchdogCode,IN UINTN DataSize,IN CHAR16 *WatchdogData OPTIONAL);

//七章五部二節に記載せらるEFI_BOOT_SERVICES.Stall()の定義
typedef EFI_STATUS (EFIAPI *EFI_STALL)(IN UINTN Microseconds);

//七章五部三節に記載せらるEFI_BOOT_SERVICES.CopyMem()の定義
typedef VOID (EFIAPI *EFI_COPY_MEM)(IN VOID *Destination,IN VOID *Source,IN UINTN Length);

//七章五部四節に記載せらるEFI_BOOT_SERVICES.SetMem()の定義
typedef VOID (EFIAPI *EFI_SET_MEM)(IN VOID *Buffer,IN UINTN Size,IN UINT8 Value);

//七章五部五節に記載せらるEFI_BOOT_SERVICES.GetNextMonotonicCount()の定義
typedef EFI_STATUS (EFIAPI *EFI_GET_NEXT_MONOTONIC_COUNT)(OUT UINT64 *Count);

//七章五部六節に記載せらるEFI_BOOT_SERVICES.InstallConfigurationTable()の定義
typedef EFI_STATUS (EFIAPI *EFI_INSTALL_CONFIGURATION_TABLE)(IN EFI_GUID *Guid,IN VOID *Table);

//七章五部七節に記載せらるEFI_BOOT_SERVICES.CalculateCrc32()の定義
typedef EFI_STATUS (EFIAPI *EFI_CALCULATE_CRC32)(IN VOID *Data,IN UINTN DataSize,OUT UINT32 *Crc32);

//八章二部一節に記載せらるGetVariable()の定義
typedef EFI_STATUS GetVariable(IN CHAR16 *VariableName,IN EFI_GUID *VendorGuid,OUT UINT32 *Attributes OPTIONAL,IN OUT UINTN *DataSize,OUT VOID *Data OPTIONAL);
#define EFI_VARIABLE_NON_VOLATILE 0x00000001
#define EFI_VARIABLE_BOOTSERVICE_ACCESS 0x00000002
#define EFI_VARIABLE_RUNTIME_ACCESS 0x00000004
#define EFI_VARIABLE_HARDWARE_ERROR_RECORD 0x00000008
//Reserved 0x00000010(将来的に何か追加の可能性があり)
#define EFI_VARIABLE_TIME_BASED_AUTHENTICATED_WRITE_ACCESS 0x00000020
#define EFI_VARIABLE_APPEND_WRITE 0x00000040
#define EFI_VARIABLE_ENHANCED_AUTHENTICATED_ACCESS 0x00000080
typedef struct{ UINT8 Type; UINT32 IdSize; }EFI_VARIABLE_AUTHENTICATION_3_CERT_ID;

//八章二部二節に記載せらるGetNextVariableName()の定義
typedef EFI_STATUS GetNextVariableName(IN OUT UINTN *VariableNameSize,IN OUT CHAR16 *VariableName,IN OUT EFI_GUID *VendorGuid);

//八章二部三節に記載せらるSetVariable()の定義
typedef EFI_TIME EFI_TIME;
typedef WIN_CERTIFICATE_UEFI_GUID WIN_CERTIFICATE_UEFI_GUID;
typedef EFI_STATUS SetVariable(IN CHAR16 *VariableName,IN EFI_GUID *VendorGuid,IN UINT32 Attributes,IN UINTN DataSize,IN VOID *Data);
typedef struct{ EFI_TIME TimeStamp; WIN_CERTIFICATE_UEFI_GUID AuthInfo; }EFI_VARIABLE_AUTHENTICATION_2;
typedef struct{ UINT8 Version; UINT8 Type; UINT32 MetadataSize; UINT32 Flags; }EFI_VARIABLE_AUTHENTICATION_3;
typedef struct{ UINT32 NonceSize; }EFI_VARIABLE_AUTHENTICATION_3_NONCE;

//八章二部四節に記載せらるQueryVariableInfo()の定義
typedef EFI_STATUS QueryVariableInfo(IN UINT32 Attributes,OUT UINT64 *MaximumVariableStorageSize,OUT UINT64 *RemainingVariableStorageSize,OUT UINT64 *MaximumVariableSize);

//八章二部七節二に記載せらるHardware Error Record Variablesの定義
#define EFI_HARDWARE_ERROR_VARIABLE {0x414E6BDD,0xE47B,0x47cc,{0xB2,0x44,0xBB,0x61,0x02,0x0C,0xF5,0x16}}

//八章三部一節に記載せらるGetTime()の定義
typedef EFI_TIME_CAPABILITIES EFI_TIME_CAPABILITIES;
typedef EFI_STATUS GetTime(OUT EFI_TIME *Time,OUT EFI_TIME_CAPABILITIES *Capabilities OPTIONAL);
typedef struct{ UINT16 Year; UINT8 Month; UINT8 Day; UINT8 Hour; UINT8 Minute; UINT8 Second; UINT8 Pad1; UINT32 Nanosecond; INT16 TimeZone; UINT8 Daylight; UINT8 Pad2; }EFI_TIME;
#define EFI_TIME_ADJUST_DAYLIGHT 0x01
#define EFI_TIME_IN_DAYLIGHT 0x02
#define EFI_UNSPECIFIED_TIMEZONE 0x07FF
typedef struct{ UINT32 Resolution; UINT32 Accuracy; BOOLEAN SetsToZero; }EFI_TIME_CAPABILITIES;

//八章三部二節に記載せらるSetTime()の定義
typedef EFI_STATUS SetTime(IN EFI_TIME *Time);

//八章三部三節に記載せらるGetWakeupTime()の定義
typedef EFI_STATUS GetWakeupTime(OUT BOOLEAN *Enabled,OUT BOOLEAN *Pending,OUT EFI_TIME *Time);

//八章三部四節に記載せらるSetWakeupTime()の定義
typedef EFI_STATUS SetWakeupTime(IN BOOLEAN Enable,IN EFI_TIME *Time OPTIONAL);

//八章四部一節に記載せらるSetVirtualAddressMap()の定義
typedef EFI_STATUS SetVirtualAddressMap(IN UINTN MemoryMapSize,IN UINTN DescriptorSize,IN UINT32 DescriptorVersion,IN EFI_MEMORY_DESCRIPTOR *VirtualMap);

//八章四部二節に記載せらるConvertPointer()の定義
typedef EFI_STATUS ConvertPointer(IN UINTN DebugDisposition,IN VOID **Address);
#define EFI_OPTIONAL_PTR 0x00000001

//八章五部一節一に記載せらるResetSystem()の定義
typedef EFI_RESET_TYPE EFI_RESET_TYPE;
typedef VOID (EFIAPI *EFI_RESET_SYSTEM)(IN EFI_RESET_TYPE ResetType,IN EFI_STATUS ResetStatus,IN UINTN DataSize,IN VOID *ResetData OPTIONAL);
typedef enum{EfiResetCold,EfiResetWarm,EfiResetShutdown,EfiResetPlatformSpecific}EFI_RESET_TYPE;

//八章五部二節一に記載せらるGetNextHighMonotonicCount()の定義
typedef EFI_STATUS GetNextHighMonotonicCount(OUT UINT32 *HighCount);

//八章五部三節一に記載せらるUpdateCapsule()の定義
typedef EFI_CAPSULE_HEADER EFI_CAPSULE_HEADER;
typedef EFI_STATUS UpdateCapsule(IN EFI_CAPSULE_HEADER **CapsuleHeaderArray,IN UINTN CapsuleCount,IN EFI_PHYSICAL_ADDRESS ScatterGatherList OPTIONAL);
typedef struct{ UINT64 Length; union{ EFI_PHYSICAL_ADDRESS DataBlock; EFI_PHYSICAL_ADDRESS ContinuationPointer; }Union; }EFI_CAPSULE_BLOCK_DESCRIPTOR;
typedef struct{ EFI_GUID CapsuleGuid; UINT32 HeaderSize; UINT32 Flags; UINT32 CapsuleImageSize; }EFI_CAPSULE_HEADER;
#define CAPSULE_FLAGS_PERSIST_ACROSS_RESET 0x00010000
#define CAPSULE_FLAGS_POPULATE_SYSTEM_TABLE 0x00020000
#define CAPSULE_FLAGS_INITIATE_RESET 0x00040000
typedef struct{ UINT32 CapsuleArrayNumber; VOID* CapsulePtr[1]; }EFI_CAPSULE_TABLE;

//八章五部三節三に記載せらるEFI_MEMORY_RANGE_CAPSULE_GUIDの定義
#define EFI_MEMORY_RANGE_CAPSULE_GUID {0xde9f0ec,0x88b6,0x428f,{0x97,0x7a,0x25,0x8f,0x1d,0xe,0x5e,0x72}}
typedef struct{ EFI_PHYSICAL_ADDRESS Address; UINT64 Length; }EFI_MEMORY_RANGE;
typedef struct{ EFI_CAPSULE_HEADER Header; UINT32 OsRequestedMemoryType; UINT64 NumberOfMemoryRanges; EFI_MEMORY_RANGE MemoryRanges[]; }EFI_MEMORY_RANGE_CAPSULE;
typedef struct{ UINT64 FirmwareMemoryRequirement; UINT64 NumberOfMemoryRanges; }EFI_MEMORY_RANGE_CAPSULE_RESULT;

//八章五部三節四に記載せらるQueryCapsuleCapabilities()の定義
typedef EFI_STATUS QueryCapsuleCapabilities( IN EFI_CAPSULE_HEADER **CapsuleHeaderArray, IN UINTN CapsuleCount, OUT UINT64 *MaximumCapsuleSize, OUT EFI_RESET_TYPE *ResetType );

//八章五部四節に記載せらるExchanging information between the OS and Firmwareの関係定義
#define EFI_OS_INDICATIONS_BOOT_TO_FW_UI 0x0000000000000001
#define EFI_OS_INDICATIONS_TIMESTAMP_REVOCATION 0x0000000000000002
#define EFI_OS_INDICATIONS_FILE_CAPSULE_DELIVERY_SUPPORTED 0x0000000000000004
#define EFI_OS_INDICATIONS_FMP_CAPSULE_SUPPORTED 0x0000000000000008
#define EFI_OS_INDICATIONS_CAPSULE_RESULT_VAR_SUPPORTED 0x0000000000000010
#define EFI_OS_INDICATIONS_START_OS_RECOVERY 0x0000000000000020
#define EFI_OS_INDICATIONS_START_PLATFORM_RECOVERY 0x0000000000000040
#define EFI_OS_INDICATIONS_JSON_CONFIG_DATA_REFRESH 0x0000000000000080

//八章五部六節一に記載せらるEFI_CAPSULE_REPORT_GUIDの定義
#define EFI_CAPSULE_REPORT_GUID {0x39b68c46,0xf7fb,0x441b,{0xb6,0xec,0x16,0xb0,0xf6,0x98,0x21,0xf3}};

//八章五部六節一ー一に記載せらるStructure of the Capsule Processing ResultVariableの定義
typedef struct{ UINT32 VariableTotalSize; UINT32 Reserved; EFI_GUID CapsuleGuid; EFI_TIME CapsuleGuid; EFI_STATUS CapsuleStatus; }EFI_CAPSULE_RESULT_VARIABLE_HEADER;

//八章五部六節一ー二に記載せらるAdditionalStructureWhenCapsuleGuidisEFI_FIRMWARE_MANAGEMENT_CAPSULE_ID_GUIDの定義
typedef struct{ UINT16 Version; UINT8 PayloadIndex; UINT8 UpdateImageIndex; EFI_GUID UpdateImageTypeId; }EFI_CAPSULE_RESULT_VARIABLE_FMP;

//八章五部六節一ー三に記載せらるAdditionalStructureWhenCapsuleGuidisEFI_JSON_CAPSULE_ID_GUIDの定義
typedef struct{ UINT32 Version; UINT32 CapsuleId; UINT32 RespLength; UINT8 Resp[]; }EFI_CAPSULE_RESULT_VARIABLE_JSON;

//九章一部一節に記載せらるEFI_LOADED_IMAGE_PROTOCOLの定義
#define EFI_LOADED_IMAGE_PROTOCOL_GUID { 0x5B1B31A1,0x9562,0x11d2,{0x8E,0x3F,0x00,0xA0,0xC9,0x69,0x72,0x3B}}
#define EFI_LOADED_IMAGE_PROTOCOL_REVISION 0x1000
typedef struct{ UINT32 Revision; EFI_HANDLE ParentHandle; EFI_SYSTEM_TABLE *SystemTable; EFI_HANDLE DeviceHandle; EFI_DEVICE_PATH_PROTOCOL *FilePath; VOID *Reserved; UINT32 LoadOptionsSize; VOID *LoadOptions; VOID *ImageBase; UINT64 ImageSize; EFI_MEMORY_TYPE ImageCodeType; EFI_MEMORY_TYPE ImageDataType; EFI_IMAGE_UNLOAD Unload; }EFI_LOADED_IMAGE_PROTOCOL;

//九章一部二節に記載せらるEFI_LOADED_IMAGE_PROTOCOL.Unload()の定義
typedef EFI_STATUS (EFIAPI *EFI_IMAGE_UNLOAD)( IN EFI_HANDLE ImageHandle );

//九章二部一節に記載せらるEFI_LOADED_IMAGE_DEVICE_PATH_PROTOCOLの定義
#define EFI_LOADED_IMAGE_DEVICE_PATH_PROTOCOL_GUID {0xbc62157e,0x3e33,0x4fec,{0x99,0x20,0x2d,0x3b,0x36,0xd7,0x50,0xdf}}

//十章二部に記載せらるEFI Device Path Protocolの定義
#define EFI_DEVICE_PATH_PROTOCOL_GUID {0x09576e91,0x6d3f,0x11d2,{0x8e,0x39,0x00,0xa0,0xc9,0x69,0x72,0x3b}}
typedef struct EFI_DEVICE_PATH_PROTOCOL { UINT8 Type; UINT8 SubType; UINT8 Length[2]; }EFI_DEVICE_PATH_PROTOCOL;

//十章三部四節十六に記載せらるVendor-Defined Messaging Device PathのGUID定義
#define EFI_PC_ANSI_GUID {0xe0c14753,0xf9be,0x11d2,{0x9a,0x0c,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
#define EFI_VT_100_GUID {0xdfa66065,0xb419,0x11d3,{0x9a,0x2d,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
#define EFI_VT_100_PLUS_GUID {0x7baec70b,0x57e0,0x4c76,{0x8e,0x87,0x2f,0x9e,0x28,0x08,0x83,0x43}}
#define EFI_VT_UTF8_GUID {0xad15a0d6,0x8bec,0x4acf,{0xa0,0x73,0xd0,0x1d,0xe7,0x7e,0x2d,0x88}}

//十章三部四節十七に記載せらるUART Flow Control Messaging Pathの定義
#define DEVICE_PATH_MESSAGING_UART_FLOW_CONTROL {0x37499a9d,0x542f,0x4c89,{0xa0,0x26,0x35,0xda,0x14,0x20,0x94,0xe4}}

//十章三部五節九に記載せらるRAM DiskのGUID定義
#define EFI_VIRTUAL_DISK_GUID {0x77AB535A,0x45FC,0x624B,{0x55,0x60,0xF7,0xB2,0x81,0xD1,0xF9,0x6E}}
#define EFI_VIRTUAL_CD_GUID {0x3D5ABD30,0x4175,0x87CE,{0x6D,0x64,0xD2,0xAD,0xE5,0x23,0xC4,0xBB}}
#define EFI_PERSISTENT_VIRTUAL_DISK_GUID {0x5CEA02C9,0x4D07,0x69D3,{0x26,0x9F,0x44,0x96,0xFB,0xE0,0x96,0xF9}}
#define EFI_PERSISTENT_VIRTUAL_CD_GUID {0x08018188,0x42CD,0xBB48,{0x10,0x0F,0x53,0x87,0xD5,0x3D,0xED,0x3D}}

//十章五部一節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOLの定義
#define EFI_DEVICE_PATH_UTILITIES_PROTOCOL_GUID {0x379be4e,0xd706,0x437d,{0xb0,0x37,0xed,0xb8,0x2f,0xb7,0x72,0xa4}}
typedef EFI_DEVICE_PATH_UTILS_GET_DEVICE_PATH_SIZE EFI_DEVICE_PATH_UTILS_GET_DEVICE_PATH_SIZE;
typedef EFI_DEVICE_PATH_UTILS_DUP_DEVICE_PATH EFI_DEVICE_PATH_UTILS_DUP_DEVICE_PATH;
typedef EFI_DEVICE_PATH_UTILS_APPEND_PATH EFI_DEVICE_PATH_UTILS_APPEND_PATH;
typedef EFI_DEVICE_PATH_UTILS_APPEND_NODE EFI_DEVICE_PATH_UTILS_APPEND_NODE;
typedef EFI_DEVICE_PATH_UTILS_APPEND_INSTANCE EFI_DEVICE_PATH_UTILS_APPEND_INSTANCE;
typedef EFI_DEVICE_PATH_UTILS_GET_NEXT_INSTANCE EFI_DEVICE_PATH_UTILS_GET_NEXT_INSTANCE;
typedef EFI_DEVICE_PATH_UTILS_IS_MULTI_INSTANCE EFI_DEVICE_PATH_UTILS_IS_MULTI_INSTANCE;
typedef EFI_DEVICE_PATH_UTILS_CREATE_NODE EFI_DEVICE_PATH_UTILS_CREATE_NODE;
typedef struct _EFI_DEVICE_PATH_UTILITIES_PROTOCOL{ EFI_DEVICE_PATH_UTILS_GET_DEVICE_PATH_SIZE GetDevicePathSize; EFI_DEVICE_PATH_UTILS_DUP_DEVICE_PATH DuplicateDevicePath; EFI_DEVICE_PATH_UTILS_APPEND_PATH AppendDevicePath; EFI_DEVICE_PATH_UTILS_APPEND_NODE AppendDeviceNode; EFI_DEVICE_PATH_UTILS_APPEND_INSTANCE AppendDevicePathInstance; EFI_DEVICE_PATH_UTILS_GET_NEXT_INSTANCE GetNextDevicePathInstance; EFI_DEVICE_PATH_UTILS_IS_MULTI_INSTANCE IsDevicePathMultiInstance; EFI_DEVICE_PATH_UTILS_CREATE_NODE CreateDeviceNode; }EFI_DEVICE_PATH_UTILITIES_PROTOCOL;

//十章五部二節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.GetDevicePathSize()の定義
typedef UINTN (EFIAPI *EFI_DEVICE_PATH_UTILS_GET_DEVICE_PATH_SIZE)( IN CONST EFI_DEVICE_PATH_PROTOCOL *DevicePath );

//十章五部三節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.DuplicateDevicePath()の定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_UTILS_DUP_DEVICE_PATH)( IN CONST EFI_DEVICE_PATH_PROTOCOL *DevicePath );

//十章五部四節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.AppendDevicePath()の定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_UTILS_APPEND_PATH)( IN CONST EFI_DEVICE_PATH_PROTOCOL *Src1, IN CONST EFI_DEVICE_PATH_PROTOCOL *Src2 );

//十章五部五節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.AppendDeviceNode()の定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_UTILS_APPEND_NODE)( IN CONST EFI_DEVICE_PATH_PROTOCOL *DevicePath, IN CONST EFI_DEVICE_PATH_PROTOCOL *DeviceNode );

//十章五部六節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.AppendDevicePathInstance()の定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_UTILS_APPEND_INSTANCE)( IN CONST EFI_DEVICE_PATH_PROTOCOL *DevicePath, IN CONST EFI_DEVICE_PATH_PROTOCOL *DevicePathInstance );

//十章五部七節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.GetNextPathInstance()の定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_UTILS_GET_NEXT_INSTANCE)( IN OUT EFI_DEVICE_PATH_PROTOCOL **DevicePathInstance, OUT UINTN *DevicePathInstanceSize OPTIONAL );

//十章五部八節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.CreateDeviceNode()の定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_UTILS_CREATE_NODE)( IN UINT8 NodeType, IN UINT8 NodeSubType, IN UINT16 NodeLength );

//十章五部九節に記載せらるEFI_DEVICE_PATH_UTILITIES_PROTOCOL.IsDevicePathMultiInstance()の定義
typedef BOOLEAN (EFIAPI *EFI_DEVICE_PATH_UTILS_IS_MULTI_INSTANCE)( IN CONST EFI_DEVICE_PATH_PROTOCOL *DevicePath );

//十章六部二節一に記載せらるEFI_DEVICE_PATH_TO_TEXT_PROTOCOLの定義
#define EFI_DEVICE_PATH_TO_TEXT_PROTOCOL_GUID {0x8b843e20,0x8132,0x4852,{0x90,0xcc,0x55,0x1a,0x4e,0x4a,0x7f,0x1c}}
typedef EFI_DEVICE_PATH_TO_TEXT_NODE EFI_DEVICE_PATH_TO_TEXT_NODE;
typedef EFI_DEVICE_PATH_TO_TEXT_PATH EFI_DEVICE_PATH_TO_TEXT_PATH;
typedef struct _EFI_DEVICE_PATH_TO_TEXT_PROTOCOL{ EFI_DEVICE_PATH_TO_TEXT_NODE ConvertDeviceNodeToText; EFI_DEVICE_PATH_TO_TEXT_PATH ConvertDevicePathToText; }EFI_DEVICE_PATH_TO_TEXT_PROTOCOL;

//十章六部三節に記載せらるEFI_DEVICE_PATH_TO_TEXT_PROTOCOL.ConvertDeviceNodeToText()の定義
typedef CHAR16* (EFIAPI *EFI_DEVICE_PATH_TO_TEXT_NODE)( IN CONST EFI_DEVICE_PATH_PROTOCOL* DeviceNode, IN BOOLEAN DisplayOnly, IN BOOLEAN AllowShortcuts );

//十章六部四節に記載せらるEFI_DEVICE_PATH_TO_TEXT_PROTOCOL.ConvertDevicePathToText()の定義
typedef CHAR16* (EFIAPI *EFI_DEVICE_PATH_TO_TEXT_PATH)( IN CONST EFI_DEVICE_PATH_PROTOCOL *DevicePath, IN BOOLEAN DisplayOnly, IN BOOLEAN AllowShortcuts );

//十章六部五節一に記載せらるEFI_DEVICE_PATH_FROM_TEXT_PROTOCOLの定義
#define EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL_GUID {0x5c99a21,0xc70f,0x4ad2,{0x8a,0x5f,0x35,0xdf,0x33,0x43,0xf5,0x1e}}
typedef EFI_DEVICE_PATH_FROM_TEXT_NODE EFI_DEVICE_PATH_FROM_TEXT_NODE;
typedef EFI_DEVICE_PATH_FROM_TEXT_PATH EFI_DEVICE_PATH_FROM_TEXT_PATH;
typedef struct _EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL{ EFI_DEVICE_PATH_FROM_TEXT_NODE ConvertTextToDevicNode; EFI_DEVICE_PATH_FROM_TEXT_PATH ConvertTextToDevicPath; }EFI_DEVICE_PATH_FROM_TEXT_PROTOCOL;

//十章六部五節二に記載せらるEFI_DEVICE_PATH_FROM_TEXT_PROTOCOL.ConvertTextToDeviceNode()の定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_FROM_TEXT_NODE)( IN CONST CHAR16* TextDeviceNode );

//十章六部五節三に記載せらるEFI_DEVICE_PATH_FROM_TEXT_PROTOCOL.ConvertTextToDevicePathの定義
typedef EFI_DEVICE_PATH_PROTOCOL* (EFIAPI *EFI_DEVICE_PATH_FROM_TEXT_PATH)( IN CONST CHAR16* TextDevicePath );

//十一章一部一節に記載せらるEFI_DRIVER_BINDING_PROTOCOLの定義
#define EFI_DRIVER_BINDING_PROTOCOL_GUID {0x18A031AB,0xB443,0x4D1A,{0xA5,0xC0,0x0C,0x09,0x26,0x1E,0x9F,0x71}}
typedef EFI_DRIVER_BINDING_PROTOCOL_SUPPORTED EFI_DRIVER_BINDING_PROTOCOL_SUPPORTED;
typedef EFI_DRIVER_BINDING_PROTOCOL_START EFI_DRIVER_BINDING_PROTOCOL_START;
typedef EFI_DRIVER_BINDING_PROTOCOL_STOP EFI_DRIVER_BINDING_PROTOCOL_STOP;
typedef struct _EFI_DRIVER_BINDING_PROTOCOL{ EFI_DRIVER_BINDING_PROTOCOL_SUPPORTED Supported; EFI_DRIVER_BINDING_PROTOCOL_START Start; EFI_DRIVER_BINDING_PROTOCOL_STOP Stop; UINT32 Version; EFI_HANDLE ImageHandle; EFI_HANDLE DriverBindingHandle; }EFI_DRIVER_BINDING_PROTOCOL;

//十一章一部二節に記載せらるEFI_DRIVER_BINDING_PROTOCOL.Supported()の定義
typedef EFI_STATUS (EFIAPI *EFI_DRIVER_BINDING_PROTOCOL_SUPPORTED)( IN EFI_DRIVER_BINDING_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_DEVICE_PATH_PROTOCOL *RemainingDevicePath OPTIONAL );

//十一章一部三節に記載せらるEFI_DRIVER_BINDING_PROTOCOL.Start()の定義
typedef EFI_STATUS (EFIAPI *EFI_DRIVER_BINDING_PROTOCOL_START)( IN EFI_DRIVER_BINDING_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_DEVICE_PATH_PROTOCOL *RemainingDevicePath OPTIONAL );

//十一章一部四節に記載せらるEFI_DRIVER_BINDING_PROTOCOL.Stop()の定義
typedef EFI_STATUS (EFIAPI *EFI_DRIVER_BINDING_PROTOCOL_STOP)( IN EFI_DRIVER_BINDING_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN UINTN NumberOfChildren, IN EFI_HANDLE *ChildHandlerBuffer OPTIONAL );

//十一章二部に記載せらるのEFI Platform Driver Override Protocolの定義
#define EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL_GUID {0x6b30c738,0xa391,0x11d4,{0x9a,0x3b,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
typedef EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER;
typedef EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH;
typedef EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED;
typedef struct _EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL{ EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER GetDriver; EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH GetDriverPath; EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED DriverLoaded; }EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL;

//十一章二部一節に記載せらるEFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL.GetDriver()の定義
typedef EFI_STATUS (EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER)( IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN OUT EFI_HANDLE *DriverImageHandle );

//十一章二部二節に記載せらるEFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL.GetDriverPath()の定義
typedef EFI_STATUS (EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH)( IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN OUT EFI_DEVICE_PATH_PROTOCOL **DriverImagePath );

//十一章二部三節に記載せらるEFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL.DriverLoaded()の定義
typedef EFI_STATUS (EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED)( IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_DEVICE_PATH_PROTOCOL *DriverImagePath, IN EFI_HANDLE DriverImageHandle );

//十一章三部一節に記載せらるEFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOLの定義
#define EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL_GUID {0x3bc1b285,0x8a15,0x4a82,{0xaa,0xbf,0x4d,0x7d,0x13,0xfb,0x32,0x65}}
typedef EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_GET_DRIVER EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_GET_DRIVER;
typedef struct _EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL{ EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_GET_DRIVER GetDriver; }EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL;

//十一章三部二節に記載せらるEFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL.GetDriver()の定義
typedef EFI_STATUS (EFIAPI *EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_GET_DRIVER)( IN EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL *This, IN OUT EFI_HANDLE *DriverImageHandle );

//十一章四部一節に記載せらるEFI_DRIVER_DIAGNOSTICS2_PROTOCOLの定義
#define EFI_DRIVER_DIAGNOSTICS_PROTOCOL_GUID {0x4d330321,0x025f,0x4aac,{0x90,0xd8,0x5e,0xd9,0x00,0x17,0x3b,0x63}}
typedef EFI_DRIVER_DIAGNOSTICS2_RUN_DIAGNOSTICS EFI_DRIVER_DIAGNOSTICS2_RUN_DIAGNOSTICS;
typedef struct _EFI_DRIVER_DIAGNOSTICS2_PROTOCOL{ EFI_DRIVER_DIAGNOSTICS2_RUN_DIAGNOSTICS RunDiagnostics; CHAR8 *SupportedLanguages; }EFI_DRIVER_DIAGNOSTICS2_PROTOCOL;

//十一章四部二節に記載せらるEFI_DRIVER_DIAGNOSTICS2_PROTOCOL.RunDiagnostics()の定義
typedef EFI_DRIVER_DIAGNOSTIC_TYPE EFI_DRIVER_DIAGNOSTIC_TYPE;
typedef EFI_STATUS (EFIAPI *EFI_DRIVER_DIAGNOSTICS2_RUN_DIAGNOSTICS)( IN EFI_DRIVER_DIAGNOSTICS2_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_HANDLE ChildHandle OPTIONAL, IN EFI_DRIVER_DIAGNOSTIC_TYPE DiagnosticType, IN IN CHAR8 *Language, OUT EFI_GUID **ErrorType, OUT UINTN *BufferSize, OUT CHAR16 **Buffer);
typedef enum{ EfiDriverDiagnosticTypeStandard = 0, EfiDriverDiagnosticTypeExtend = 1, EfiDriverDiagnosticTypeManufacturing = 2, EfiDriverDiagnosticTypeCancel = 3, EfiDriverDiagnosticTypeMaximum }EFI_DRIVER_DIAGNOSTIC_TYPE;

//十一章五部一節に記載せらるEFI_COMPONENT_NAME2_PROTOCOLの定義
#define EFI_COMPONENT_NAME2_PROTOCOL_GUID {0x6a7a5cff,0xe8d9,0x4f70,{0xba,0xda,0x75,0xab,0x30,0x25,0xce,0x14}}
typedef EFI_COMPONENT_NAME_GET_DRIVER_NAME EFI_COMPONENT_NAME_GET_DRIVER_NAME;
typedef EFI_COMPONENT_NAME_GET_CONTROLLER_NAME EFI_COMPONENT_NAME_GET_CONTROLLER_NAME;
typedef struct _EFI_COMPONENT_NAME2_PROTOCOL{ EFI_COMPONENT_NAME_GET_DRIVER_NAME GetDriverName; EFI_COMPONENT_NAME_GET_CONTROLLER_NAME GetControllerName; CHAR8 *SupportedLanguages; }EFI_COMPONENT_NAME2_PROTOCOL;

//十一章五部二節に記載せらるEFI_COMPONENT_NAME2_PROTOCOL.GetDriverName()の定義
typedef EFI_STATUS (EFIAPI *EFI_COMPONENT_NAME_GET_DRIVER_NAME)( IN EFI_COMPONENT_NAME2_PROTOCOL *This, IN CHAR8 *Language, OUT CHAR16 **DriverName);

//十一章五部三節に記載せらるEFI_COMPONENT_NAME2_PROTOCOL.GetControllerName()の定義
typedef EFI_STATUS (EFIAPI *EFI_COMPONENT_NAME_GET_CONTROLLER_NAME)( IN EFI_COMPONENT_NAME2_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_HANDLE ChildHandle OPTIONAL, IN CHAR8 *Language, OUT CHAR16 **ControllerName );

//十一章六部一節に記載せらるEFI_SERVICE_BINDING_PROTOCOLの定義
typedef EFI_SERVICE_BINDING_CREATE_CHILD EFI_SERVICE_BINDING_CREATE_CHILD;
typedef EFI_SERVICE_BINDING_DESTROY_CHILD EFI_SERVICE_BINDING_DESTROY_CHILD;
typedef struct _EFI_SERVICE_BINDING_PROTOCOL{ EFI_SERVICE_BINDING_CREATE_CHILD CreateChild; EFI_SERVICE_BINDING_DESTROY_CHILD DestroyChild; }EFI_SERVICE_BINDING_PROTOCOL;

//十一章六部二節に記載せらるEFI_SERVICE_BINDING_PROTOCOL.CreateChild()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERVICE_BINDING_CREATE_CHILD)( IN EFI_SERVICE_BINDING_PROTOCOL *This, IN OUT EFI_HANDLE *ChildHandle );

//十一章六部三節に記載せらるEFI_SERVICE_BINDING_PROTOCOL.DestroyChild()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERVICE_BINDING_DESTROY_CHILD)( IN EFI_SERVICE_BINDING_PROTOCOL *This, IN EFI_HANDLE ChildHandle );

//十一章七部一節に記載せらるEFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOLの定義
#define EFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL_GUID {0x642cd590,0x8059,0x4c0a,{0xa9,0x58,0xc5,0xec,0x07,0xd2,0x3c,0x4b}}
typedef EFI_PLATFORM_TO_DRIVER_CONFIGURATION_QUERY EFI_PLATFORM_TO_DRIVER_CONFIGURATION_QUERY;
typedef EFI_PLATFORM_TO_DRIVER_CONFIGURATION_RESPONSE EFI_PLATFORM_TO_DRIVER_CONFIGURATION_RESPONSE;
typedef struct _EFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL{ EFI_PLATFORM_TO_DRIVER_CONFIGURATION_QUERY Query; EFI_PLATFORM_TO_DRIVER_CONFIGURATION_RESPONSE Response; }EFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL;

//十一章七部二節に記載せらるEFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL.Query()の定義
typedef EFI_STATUS (EFIAPI *EFI_PLATFORM_TO_DRIVER_CONFIGURATION_QUERY)( IN EFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_HANDLE ChildHandle OPTIONAL, IN UINTN *Instance, IN EFI_GUID **ParameterTypeGuid, OUT VOID **ParameterBlock, OUT UINTN *ParameterBlockSize );

//十一章七部三節に記載せらるEFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL.Response()の定義
typedef EFI_PLATFORM_CONFIGURATION_ACTION EFI_PLATFORM_CONFIGURATION_ACTION;
typedef EFI_STATUS (EFIAPI *EFI_PLATFORM_TO_DRIVER_CONFIGURATION_RESPONSE)( IN EFI_PLATFORM_TO_DRIVER_CONFIGURATION_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_HANDLE ChildHandle OPTIONAL, IN UINTN *Instance, IN EFI_GUID *ParameterTypeGuid, IN VOID *ParameterBlock, IN UINTN ParameterBlockSize, IN EFI_PLATFORM_CONFIGURATION_ACTION ConfigurationAction );
typedef enum { EfiPlatformConfigurationActionNone = 0, EfiPlatformConfigurationActionStopController = 1, EfiPlatformConfigurationActionRestartController = 2, EfiPlatformConfigurationActionRestartPlatform = 3, EfiPlatformConfigurationActionNvramFailed = 4, EfiPlatformConfigurationActionUnsupportedGuid = 5, EfiPlatformConfigurationActionMaximum }EFI_PLATFORM_CONFIGURATION_ACTION;

//十一章七部四節に記載せらるDMTF SM CLP ParameterTypeGuidの定義
#define EFI_PLATFORM_TO_DRIVER_CONFIGURATION_CLP_GUID {0x345ecc0e,0xcb6,0x4b75,{0xbb,0x57,0x1b,0x12,0x9c,0x47,0x33,0x3e}}
typedef struct { CHAR8 *CLPCommand; UINT32 CLPCommandLength; CHAR8 *CLPReturnString; UINT32 CLPReturnStringLength; UINT8 CLPCmdStatus; UINT8 CLPErrorValue; UINT16 CLPMsgCode; }EFI_CONFIGURE_CLP_PARAMETER_BLK;

//十一章八部一節に記載せらるEFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOLの定義
#define EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL_GUID {0x5c198761,0x16a8,0xe69,{0x97,0x2c,0x89,0xd6,0x79,0x54,0xf8,0x1d}}
typedef struct _EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL{ UINT32 Length; UINT32 FirmwareVersion; }EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL;

//十一章九部一節一に記載せらるEFI_DRIVER_FAMILY_OVERRIDE_PROTOCOLの定義
#define EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL_GUID {0xb1ee129e,0xda36,0x4181,{0x91,0xf8,0x04,0xa4,0x92,0x37,0x66,0xa7}}
typedef EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION;
typedef struct _EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL{ EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION GetVersion; }EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL;

//十一章九部一節二に記載せらるEFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL.GetVersion()の定義
typedef UINT32 (EFIAPI *EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION)( IN EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL *This );

//十一章十部一節に記載せらるEFI_DRIVER_HEALTH_PROTOCOLの定義
#define EFI_DRIVER_HEALTH_PROTOCOL_GUID {0x2a534210,0x9280,0x41d8,{0xae,0x79,0xca,0xda,0x01,0xa2,0xb1,0x27}}
typedef EFI_DRIVER_HEALTH_GET_HEALTH_STATUS EFI_DRIVER_HEALTH_GET_HEALTH_STATUS;
typedef EFI_DRIVER_HEALTH_REPAIR EFI_DRIVER_HEALTH_REPAIR;
typedef struct _EFI_DRIVER_HEALTH_PROTOCOL{ EFI_DRIVER_HEALTH_GET_HEALTH_STATUS GetHealthStatus; EFI_DRIVER_HEALTH_REPAIR Repair; }EFI_DRIVER_HEALTH_PROTOCOL;

//十一章十部二節に記載せらるEFI_DRIVER_HEALTH_PROTOCOL.GetHealthStatus()の定義
typedef EFI_DRIVER_HEALTH_STATUS EFI_DRIVER_HEALTH_STATUS;
typedef EFI_DRIVER_HEALTH_HII_MESSAGE EFI_DRIVER_HEALTH_HII_MESSAGE;
typedef EFI_HII_HANDLE EFI_HII_HANDLE;
typedef EFI_STATUS (EFIAPI *EFI_DRIVER_HEALTH_GET_HEALTH_STATUS)( IN EFI_DRIVER_HEALTH_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, OPTIONAL IN EFI_HANDLE ChildHandle, OPTIONAL OUT EFI_DRIVER_HEALTH_STATUS *HealthStatus, OUT EFI_DRIVER_HEALTH_HII_MESSAGE **MessageList, OPTIONAL OUT EFI_HII_HANDLE *FormHiiHandle OPTIONAL );
typedef enum{ EfiDriverHealthStatusHealthy, EfiDriverHealthStatusRepairRequired, EfiDriverHealthStatusConfigurationRequired, EfiDriverHealthStatusFailed, EfiDriverHealthStatusReconnectRequired, EfiDriverHealthStatusRebootRequired }EFI_DRIVER_HEALTH_STATUS;

//十一章十部三節に記載せらるEFI_DRIVER_HEALTH_PROTOCOL.Repair()の定義
typedef EFI_DRIVER_HEALTH_REPAIR_NOTIFY EFI_DRIVER_HEALTH_REPAIR_NOTIFY;
typedef EFI_STATUS (EFIAPI *EFI_DRIVER_HEALTH_REPAIR)( IN EFI_DRIVER_HEALTH_PROTOCOL *This, IN EFI_HANDLE ControllerHandle, IN EFI_HANDLE ChildHandle OPTIONAL, IN EFI_DRIVER_HEALTH_REPAIR_NOTIFY RepairNotify OPTIONAL );
typedef EFI_STATUS (EFIAPI *EFI_DRIVER_HEALTH_REPAIR_NOTIFY)( IN UINTN Value, IN UINTN Limit );

//十一章十一部一節に記載せらるEFI_ADAPTER_INFORMATION_PROTOCOLの定義
#define EFI_ADAPTER_INFORMATION_PROTOCOL_GUID {0xE5DD1403,0xD622,0xC24E,{0x84,0x88,0xC7,0x1B,0x17,0xF5,0xE8,0x02}}
typedef EFI_ADAPTER_INFO_GET_INFO EFI_ADAPTER_INFO_GET_INFO;
typedef EFI_ADAPTER_INFO_SET_INFO EFI_ADAPTER_INFO_SET_INFO;
typedef EFI_ADAPTER_INFO_GET_SUPPORTED_TYPES EFI_ADAPTER_INFO_GET_SUPPORTED_TYPES;
typedef struct _EFI_ADAPTER_INFORMATION_PROTOCOL{ EFI_ADAPTER_INFO_GET_INFO GetInformation; EFI_ADAPTER_INFO_SET_INFO SetInformation; EFI_ADAPTER_INFO_GET_SUPPORTED_TYPES GetSupportedTypes; }EFI_ADAPTER_INFORMATION_PROTOCOL;

//十一章十一部二節に記載せらるEFI_ADAPTER_INFORMATION_PROTOCOL.GetInformation()の定義
typedef EFI_STATUS (EFIAPI *EFI_ADAPTER_INFO_GET_INFO)( IN EFI_ADAPTER_INFORMATION_PROTOCOL *This, IN EFI_GUID *InformationType, OUT VOID **InformationBlock, OUT UINTN *InformationBlockSize );

//十一章十一部三節に記載せらるEFI_ADAPTER_INFORMATION_PROTOCOL.SetInformation()の定義
typedef EFI_STATUS (EFIAPI *EFI_ADAPTER_INFO_SET_INFO)( IN EFI_ADAPTER_INFORMATION_PROTOCOL *This, IN EFI_GUID *InformationType, IN VOID *InformationBlock, IN UINTN InformationBlockSize );

//十一章十一部四節に記載せらるEFI_ADAPTER_INFORMATION_PROTOCOL.GetSupportedTypes()の定義
typedef EFI_STATUS (EFIAPI *EFI_ADAPTER_INFO_GET_SUPPORTED_TYPES)( IN EFI_ADAPTER_INFORMATION_PROTOCOL *This, OUT EFI_GUID **InfoTypesBuffer, OUT UINTN *InfoTypesBufferCount );

//十一章十二部一節に記載せらるNetwork Media StateのGUID及び構造体の定義
#define EFI_ADAPTER_INFO_MEDIA_STATE_GUID {0xD7C74207,0xA831,0x4A26,{0xB1,0xF5,0xD1,0x93,0x06,0x5C,0xE8,0xB6}}
typedef struct{ EFI_STATUS MediaState; }EFI_ADAPTER_INFO_MEDIA_STATE;

//十一章十二部二節に記載せらるNetwork BootのGUID及び構造体の定義
#define EFI_ADAPTER_INFO_NETWORK_BOOT_GUID {0x1FBD2960,0x4130,0x41E5,{0x94,0xAC,0xD2,0xCF,0x03,0x7F,0xB3,0x7C}}
typedef struct{ BOOLEAN iSsciIpv4BootCapablity; BOOLEAN iScsiIpv6BootCapablity; BOOLEAN FCoeBootCapablity; BOOLEAN OffloadCapability; BOOLEAN iScsiMpioCapability; BOOLEAN iScsiIpv4Boot; BOOLEAN iScsiIpv6Boot; BOOLEAN FCoeBoot; }EFI_ADAPTER_INFO_NETWORK_BOOT;

//十一章十二部三節に記載せらるSAN MAC AddressのGUID及び構造体の定義
#define EFI_ADAPTER_INFO_SAN_MAC_ADDRESS_GUID {0x114da5ef,0x2cf1,0x4e12,{0x9b,0xbb,0xc4,0x70,0xb5,0x52,0x05,0xd9}}
typedef struct{ EFI_MAC_ADDRESS SanMacAddress; }EFI_ADAPTER_INFO_SAN_MAC_ADDRESS;

//十一章十二部四節に記載せらるIPV6 Support from UNDIのGUID及び構造体の定義
#define EFI_ADAPTER_INFO_UNDI_IPV6_SUPPORT_GUID {0x4bd56be3,0x4975,0x4d8a,{0xa0,0xad,0xc4,0x91,0x20,0x4b,0x5d,0x4d}}
typedef struct{ BOOLEAN Ipv6Support; }EFI_ADAPTER_INFO_UNDI_IPV6_SUPPORT;

//十一章十二部五節に記載せらるNetwork Media TypeのGUID及び構造体の定義
#define EFI_ADAPTER_INFO_MEDIA_TYPE_GUID {0x8484472f,0x71ec,0x411a,{0xb3,0x9c,0x62,0xcd,0x94,0xd9,0x91,0x6e}}
typedef struct{ UINT8 MediaType; }EFI_ADAPTER_INFO_MEDIA_TYPE;

//十一章十二部六節に記載せらるCoherent Device Attribute Table(CDAT) TypeのGUID及び構造体の定義
#define EFI_ADAPTER_INFO_CDAT_TYPE_GUID {0x77af24d1,0xb6f0,0x42b9,{0x83,0xf5,0x8f,0xe6,0xe8,0x3e,0xb6,0xf0}}
typedef struct{ UINTN CdatSize; UINT8 Cdat[]; }EFI_ADAPTER_INFO_CDAT_TYPE_TYPE;

//十二章二部一節に記載せらるEFI_SIMPLE_TEXT_INPUT_EX_PROTOCOLの定義
#define EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL_GUID {0xdd9e7534,0x7762,0x4698,{0x8c,0x14,0xf5,0x85,0x17,0xa6,0x25,0xaa}}
typedef EFI_INPUT_RESET_EX EFI_INPUT_RESET_EX;
typedef EFI_INPUT_READ_KEY_EX EFI_INPUT_READ_KEY_EX;
typedef EFI_SET_STATE EFI_SET_STATE;
typedef EFI_REGISTER_KEYSTROKE_NOTIFY EFI_REGISTER_KEYSTROKE_NOTIFY;
typedef EFI_UNREGISTER_KEYSTROKE_NOTIFY EFI_UNREGISTER_KEYSTROKE_NOTIFY;
typedef struct _EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL{ EFI_INPUT_RESET_EX Reset; EFI_INPUT_READ_KEY_EX ReadKeyStrokeEx; EFI_EVENT WaitForKeyEx; EFI_SET_STATE SetState; EFI_REGISTER_KEYSTROKE_NOTIFY RegisterKeyNotify; EFI_UNREGISTER_KEYSTROKE_NOTIFY UnregisterKeyNotify; }EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL;

//十二章二部二節に記載せらるEFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL.Reset()の定義
typedef EFI_STATUS (EFIAPI *EFI_INPUT_RESET_EX)( IN EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, IN BOOLEAN ExtendedVerification );

//十二章二部三節に記載せらるEFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL.ReadKeyStrokeEx()の定義
typedef EFI_KEY_DATA EFI_KEY_DATA;
typedef EFI_KEY_STATE EFI_KEY_STATE;
typedef UINT8 EFI_KEY_TOGGLE_STATE;
typedef EFI_STATUS (EFIAPI *EFI_INPUT_READ_KEY_EX)( IN EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, OUT EFI_KEY_DATA *KeyData );
typedef struct{ EFI_INPUT_KEY Key; EFI_KEY_STATE KeyState; }EFI_KEY_DATA;
typedef struct EFI_KEY_STATE{ UINT32 KeyShiftState; EFI_KEY_TOGGLE_STATE KeyToggleState; }EFI_KEY_STATE;
#define EFI_SHIFT_STATE_VALID 0x80000000
#define EFI_RIGHT_SHIFT_PRESSED 0x00000001
#define EFI_LEFT_SHIFT_PRESSED 0x00000002
#define EFI_RIGHT_CONTROL_PRESSED 0x00000004
#define EFI_LEFT_CONTROL_PRESSED 0x00000008
#define EFI_RIGHT_ALT_PRESSED 0x00000010
#define EFI_LEFT_ALT_PRESSED 0x00000020
#define EFI_RIGHT_LOGO_PRESSED 0x00000040
#define EFI_LEFT_LOGO_PRESSED 0x00000080
#define EFI_MENU_KEY_PRESSED 0x00000100
#define EFI_SYS_REQ_PRESSED 0x00000200
#define EFI_TOGGLE_STATE_VALID 0x80
#define EFI_KEY_STATE_EXPOSED 0x40
#define EFI_SCROLL_LOCK_ACTIVE 0x01
#define EFI_NUM_LOCK_ACTIVE 0x02
#define EFI_CAPS_LOCK_ACTIVE 0x04

//十二章二部四節に記載せらるEFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL.SetState()の定義
typedef EFI_STATUS (EFIAPI *EFI_SET_STATE)( IN EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, IN EFI_KEY_TOGGLE_STATE *KeyToggleState );

//十二章二部五節に記載せらるEFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL.RegisterKeyNotify()の定義
typedef EFI_KEY_NOTIFY_FUNCTION EFI_KEY_NOTIFY_FUNCTION;
typedef EFI_STATUS (EFIAPI *EFI_REGISTER_KEYSTROKE_NOTIFY)( IN EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, IN EFI_KEY_DATA *KeyData, IN EFI_KEY_NOTIFY_FUNCTION KeyNotificationFunction, OUT VOID **NotifyHandle );
typedef EFI_STATUS (EFIAPI *EFI_KEY_NOTIFY_FUNCTION)( IN EFI_KEY_DATA *KeyData );

//十二章二部六節に記載せらるEFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL.UnregisterKeyNotify()の定義
typedef EFI_STATUS (EFIAPI *EFI_UNREGISTER_KEYSTROKE_NOTIFY)( IN EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL *This, IN VOID *NotificationHandle );

//十二章三部一節に記載せらるEFI_SIMPLE_TEXT_INPUT_PROTOCOLの定義
#define EFI_SIMPLE_TEXT_INPUT_PROTOCOL_GUID {0x387477c1,0x69c7,0x11d2,{0x8e,0x39,0x00,0xa0,0xc9,0x69,0x72,0x3b}}
typedef EFI_INPUT_RESET EFI_INPUT_RESET;
typedef EFI_INPUT_READ_KEY EFI_INPUT_READ_KEY;
typedef struct _EFI_SIMPLE_TEXT_INPUT_PROTOCOL{ EFI_INPUT_RESET Reset; EFI_INPUT_READ_KEY ReadKeyStroke; EFI_EVENT WaitForKey; }EFI_SIMPLE_TEXT_INPUT_PROTOCOL;

//十二章三部二節に記載せらるEFI_SIMPLE_TEXT_INPUT_PROTOCOL.Reset()の定義
typedef EFI_STATUS (EFIAPI *EFI_INPUT_RESET)( IN EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This, IN BOOLEAN ExtendedVerification );

//十二章三部三節に記載せらるEFI_SIMPLE_TEXT_INPUT_PROTOCOL.ReadKeyStroke()の定義
typedef EFI_INPUT_KEY EFI_INPUT_KEY;
typedef EFI_STATUS (EFIAPI *EFI_INPUT_READ_KEY)( IN EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This, OUT EFI_INPUT_KEY *Key );
typedef struct{ UINT16 ScanCode; CHAR16 UnicodeChar; }EFI_INPUT_KEY;

//十二章四部一節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOLの定義
#define EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL_GUID {0x387477c2,0x69c7,0x11d2,{0x8e,0x39,0x00,0xa0,0xc9,0x69,0x72,0x3b}}
typedef EFI_TEXT_RESET EFI_TEXT_RESET;
typedef EFI_TEXT_STRING EFI_TEXT_STRING;
typedef EFI_TEXT_TEST_STRING EFI_TEXT_TEST_STRING;
typedef EFI_TEXT_QUERY_MODE EFI_TEXT_QUERY_MODE;
typedef EFI_TEXT_SET_MODE EFI_TEXT_SET_MODE;
typedef EFI_TEXT_SET_ATTRIBUTE EFI_TEXT_SET_ATTRIBUTE;
typedef EFI_TEXT_CLEAR_SCREEN EFI_TEXT_CLEAR_SCREEN;
typedef EFI_TEXT_SET_CURSOR_POSITION EFI_TEXT_SET_CURSOR_POSITION;
typedef EFI_TEXT_ENABLE_CURSOR EFI_TEXT_ENABLE_CURSOR;
typedef SIMPLE_TEXT_OUTPUT_MODE SIMPLE_TEXT_OUTPUT_MODE;
typedef struct _EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL{ EFI_TEXT_RESET Reset; EFI_TEXT_STRING OutputString; EFI_TEXT_TEST_STRING TestString; EFI_TEXT_QUERY_MODE QueryMode; EFI_TEXT_SET_MODE SetMode; EFI_TEXT_SET_ATTRIBUTE SetAttribute; EFI_TEXT_CLEAR_SCREEN ClearScreen; EFI_TEXT_SET_CURSOR_POSITION SetCursorPosition; EFI_TEXT_ENABLE_CURSOR EnableCursor; SIMPLE_TEXT_OUTPUT_MODE *Mode; }EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL;
typedef struct{ INT32 MaxMode; INT32 Mode; INT32 Attribute; INT32 CursorColumn; INT32 CursorRow; BOOLEAN CursorVisible; }SIMPLE_TEXT_OUTPUT_MODE;

//十二章四部二節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.Reset()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_RESET)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN BOOLEAN ExtendedVerification );

//十二章四部三節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.OutputString()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_STRING)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN CHAR16 *String );
#define BOXDRAW_HORIZONTAL 0x2500
#define BOXDRAW_VERTICAL 0x2502
#define BOXDRAW_DOWN_RIGHT 0x250c
#define BOXDRAW_DOWN_LEFT 0x2510
#define BOXDRAW_UP_RIGHT 0x2514
#define BOXDRAW_UP_LEFT 0x2518
#define BOXDRAW_VERTICAL_RIGHT 0x251c
#define BOXDRAW_VERTICAL_LEFT 0x2524
#define BOXDRAW_DOWN_HORIZONTAL 0x252c
#define BOXDRAW_UP_HORIZONTAL 0x2534
#define BOXDRAW_VERTICAL_HORIZONTAL 0x253c
#define BOXDRAW_DOUBLE_HORIZONTAL 0x2550
#define BOXDRAW_DOUBLE_VERTICAL 0x2551
#define BOXDRAW_DOWN_RIGHT_DOUBLE 0x2552
#define BOXDRAW_DOWN_DOUBLE_RIGHT 0x2553
#define BOXDRAW_DOUBLE_DOWN_RIGHT 0x2554
#define BOXDRAW_DOWN_LEFT_DOUBLE 0x2555
#define BOXDRAW_DOWN_DOUBLE_LEFT 0x2556
#define BOXDRAW_DOUBLE_DOWN_LEFT 0x2557
#define BOXDRAW_UP_RIGHT_DOUBLE 0x2558
#define BOXDRAW_UP_DOUBLE_RIGHT 0x2559
#define BOXDRAW_DOUBLE_UP_RIGHT 0x255a
#define BOXDRAW_UP_LEFT_DOUBLE 0x255b
#define BOXDRAW_UP_DOUBLE_LEFT 0x255c
#define BOXDRAW_DOUBLE_UP_LEFT 0x255d
#define BOXDRAW_VERTICAL_RIGHT_DOUBLE 0x255e
#define BOXDRAW_VERTICAL_DOUBLE_RIGHT 0x255f
#define BOXDRAW_DOUBLE_VERTICAL_RIGHT 0x2560
#define BOXDRAW_VERTICAL_LEFT_DOUBLE 0x2561
#define BOXDRAW_VERTICAL_DOUBLE_LEFT 0x2562
#define BOXDRAW_DOUBLE_VERTICAL_LEFT 0x2563
#define BOXDRAW_DOWN_HORIZONTAL_DOUBLE 0x2564
#define BOXDRAW_DOWN_DOUBLE_HORIZONTAL 0x2565
#define BOXDRAW_DOUBLE_DOWN_HORIZONTAL 0x2566
#define BOXDRAW_UP_HORIZONTAL_DOUBLE 0x2567
#define BOXDRAW_UP_DOUBLE_HORIZONTAL 0x2568
#define BOXDRAW_DOUBLE_UP_HORIZONTAL 0x2569
#define BOXDRAW_VERTICAL_HORIZONTAL_DOUBLE 0x256a
#define BOXDRAW_VERTICAL_DOUBLE_HORIZONTAL 0x256b
#define BOXDRAW_DOUBLE_VERTICAL_HORIZONTAL 0x256c
#define GEOMETRICSHAPE_UP_TRIANGLE 0x25b2
#define GEOMETRICSHAPE_RIGHT_TRIANGLE 0x25ba
#define GEOMETRICSHAPE_DOWN_TRIANGLE 0x25bc
#define GEOMETRICSHAPE_LEFT_TRIANGLE 0x25c4
#define ARROW_UP 0x2191
#define ARROW_DOWN 0x2193

//十二章四部四節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.TestString()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_TEST_STRING)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN CHAR16 *String );

//十二章四部五節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.QueryMode()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_QUERY_MODE)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN UINTN ModeNumber, OUT UINTN *Columns, OUT UINTN *Rows );

//十二章四部六節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.SetMode()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_SET_MODE)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN UINTN ModeNumber );

//十二章四部七節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.SetAttribute()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_SET_ATTRIBUTE)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN UINTN Attribute );
#define EFI_BLACK 0x00
#define EFI_BLUE 0x01
#define EFI_GREEN 0x02
#define EFI_CYAN 0x03
#define EFI_RED 0x04
#define EFI_MAGENTA 0x05
#define EFI_BROWN 0x06
#define EFI_LIGHTGRAY 0x07
#define EFI_BRIGHT 0x08
#define EFI_DARKGRAY (EFI_BLACK | EFI_BRIGHT)
#define EFI_LIGHTBLUE 0x09
#define EFI_LIGHTGREEN 0x0A
#define EFI_LIGHTCYAN 0x0B
#define EFI_LIGHTRED 0x0C
#define EFI_LIGHTMAGENTA 0x0D
#define EFI_YELLOW 0x0E
#define EFI_WHITE 0x0F
#define EFI_BACKGROUND_BLACK 0x00
#define EFI_BACKGROUND_BLUE 0x10
#define EFI_BACKGROUND_GREEN 0x20
#define EFI_BACKGROUND_CYAN 0x30
#define EFI_BACKGROUND_RED 0x40
#define EFI_BACKGROUND_MAGENTA 0x50
#define EFI_BACKGROUND_BROWN 0x60
#define EFI_BACKGROUND_LIGHTGRAY 0x70
#define EFI_TEXT_ATTR(Foreground,Background) ((Foreground) | ((Background) << 4))

//十二章四部八節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.ClearScreen()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_CLEAR_SCREEN)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This );

//十二章四部九節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.SetCursorPosition()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_SET_CURSOR_POSITION)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN UINTN Column, IN UINTN Row );

//十二章四部十節に記載せらるEFI_SIMPLE_TEXT_OUTPUT_PROTOCOL.EnableCursor()の定義
typedef EFI_STATUS (EFIAPI *EFI_TEXT_ENABLE_CURSOR)( IN EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This, IN BOOLEAN Visible );

//十二章五部一節に記載せらるEFI_SIMPLE_POINTER_PROTOCOLの定義
#define EFI_SIMPLE_POINTER_PROTOCOL_GUID {0x31878c87,0xb75,0x11d5,{0x9a,0x4f,0x00,0x90,0x27,0x3f,0xc1,0x4d}}
typedef EFI_SIMPLE_POINTER_RESET EFI_SIMPLE_POINTER_RESET;
typedef EFI_SIMPLE_POINTER_GET_STATE EFI_SIMPLE_POINTER_GET_STATE;
typedef EFI_SIMPLE_POINTER_MODE EFI_SIMPLE_POINTER_MODE;
typedef struct _EFI_SIMPLE_POINTER_PROTOCOL{ EFI_SIMPLE_POINTER_RESET Reset; EFI_SIMPLE_POINTER_GET_STATE GetState; EFI_EVENT WaitForInput; EFI_SIMPLE_POINTER_MODE *Mode; }EFI_SIMPLE_POINTER_PROTOCOL;
typedef struct{ UINT64 ResolutionX; UINT64 ResolutionY; UINT64 ResolutionZ; BOOLEAN LeftButton; BOOLEAN RightButton; }EFI_SIMPLE_POINTER_MODE;

//十二章五部二節に記載せらるEFI_SIMPLE_POINTER_PROTOCOL.Reset()の定義
typedef EFI_STATUS (EFIAPI *EFI_SIMPLE_POINTER_RESET)( IN EFI_SIMPLE_POINTER_PROTOCOL *This, IN BOOLEAN ExtendedVerification );

//十二章五部三節に記載せらるEFI_SIMPLE_POINTER_PROTOCOL.GetState()の定義
typedef EFI_SIMPLE_POINTER_STATE EFI_SIMPLE_POINTER_STATE;
typedef EFI_STATUS (EFIAPI *EFI_SIMPLE_POINTER_GET_STATE)( IN EFI_SIMPLE_POINTER_PROTOCOL *This, OUT EFI_SIMPLE_POINTER_STATE *State );
typedef struct{ INT32 RelativeMovementX; INT32 RelativeMovementY; INT32 RelativeMovementZ; BOOLEAN LeftButton; BOOLEAN RightButton; }EFI_SIMPLE_POINTER_STATE;

//十二章七部一節に記載せらるEFI_ABSOLUTE_POINTER_PROTOCOLの定義
#define EFI_ABSOLUTE_POINTER_PROTOCOL_GUID {0x8D59D32B,0xC655,0x4AE9,{0x9B,0x15,0xF2,0x59,0x04,0x99,0x2A,0x43}}
typedef EFI_ABSOLUTE_POINTER_RESET EFI_ABSOLUTE_POINTER_RESET;
typedef EFI_ABSOLUTE_POINTER_GET_STATE EFI_ABSOLUTE_POINTER_GET_STATE;
typedef EFI_ABSOLUTE_POINTER_MODE EFI_ABSOLUTE_POINTER_MODE;
typedef struct _EFI_ABSOLUTE_POINTER_PROTOCOL{ EFI_ABSOLUTE_POINTER_RESET Reset; EFI_ABSOLUTE_POINTER_GET_STATE GetState; EFI_EVENT WaitForInput; EFI_ABSOLUTE_POINTER_MODE *Mode; }EFI_ABSOLUTE_POINTER_PROTOCOL;
typedef struct{ UINT64 AbsoluteMinX; UINT64 AbsoluteMinY; UINT64 AbsoluteMinZ; UINT64 AbsoluteMaxX; UINT64 AbsoluteMaxY; UINT64 AbsoluteMaxZ; UINT32 Attributes; }EFI_ABSOLUTE_POINTER_MODE;
#define EFI_ABSP_SupportsAltActive 0x00000001
#define EFI_ABSP_SupportsPressureAsZ 0x00000002

//十二章七部二節に記載せらるEFI_ABSOLUTE_POINTER_PROTOCOL.Reset()の定義
typedef EFI_STATUS (EFIAPI *EFI_ABSOLUTE_POINTER_RESET)( IN EFI_ABSOLUTE_POINTER_PROTOCOL *This, IN BOOLEAN ExtendedVerification );

//十二章七部三節に記載せらるEFI_ABSOLUTE_POINTER_PROTOCOL.GetState()の定義
typedef EFI_ABSOLUTE_POINTER_STATE EFI_ABSOLUTE_POINTER_STATE;
typedef EFI_STATUS (EFIAPI *EFI_ABSOLUTE_POINTER_GET_STATE)( IN EFI_ABSOLUTE_POINTER_PROTOCOL *This, OUT EFI_ABSOLUTE_POINTER_STATE *State );
typedef struct{ UINT64 CurrentX; UINT64 CurrentY; UINT64 CurrentZ; UINT32 ActiveButtons; }EFI_ABSOLUTE_POINTER_STATE;
#define EFI_ABSP_TouchActive 0x00000001
#define EFI_ABS_AltActive 0x00000002

//十二章八部一節に記載せらるEFI_SERIAL_IO_PROTOCOLの定義
#define EFI_SERIAL_IO_PROTOCOL_GUID {0xBB25CF6F,0xF1D4,0x11D2,{0x9a,0x0c,0x00,0x90,0x27,0x3f,0xc1,0xfd}}
#define EFI_SERIAL_IO_PROTOCOL_REVISION 0x00010000
#define EFI_SERIAL_IO_PROTOCOL_REVISION1p1 0x00010001
typedef EFI_SERIAL_RESET EFI_SERIAL_RESET;
typedef EFI_SERIAL_SET_ATTRIBUTES EFI_SERIAL_SET_ATTRIBUTES;
typedef EFI_SERIAL_SET_CONTROL_BITS EFI_SERIAL_SET_CONTROL_BITS;
typedef EFI_SERIAL_GET_CONTROL_BITS EFI_SERIAL_GET_CONTROL_BITS;
typedef EFI_SERIAL_WRITE EFI_SERIAL_WRITE;
typedef EFI_SERIAL_READ EFI_SERIAL_READ;
typedef SERIAL_IO_MODE SERIAL_IO_MODE;
typedef struct{ UINT32 Revision; EFI_SERIAL_RESET Reset; EFI_SERIAL_SET_ATTRIBUTES SetAttributes; EFI_SERIAL_SET_CONTROL_BITS SetControl; EFI_SERIAL_GET_CONTROL_BITS GetControl; EFI_SERIAL_WRITE Write; EFI_SERIAL_READ Read; SERIAL_IO_MODE *Mode; CONST EFI_GUID *DeviceTypeGuid; }EFI_SERIAL_IO_PROTOCOL;
typedef struct{ UINT32 ControlMask; UINT32 Timeout; UINT64 BaudRate; UINT32 ReceiveFifoDepth; UINT32 DataBits; UINT32 Parity; UINT32 StopBits; }SERIAL_IO_MODE;
typedef EFI_PARITY_TYPE EFI_PARITY_TYPE;
typedef EFI_STOP_BITS_TYPE EFI_STOP_BITS_TYPE;
typedef enum{ DefaultParity, NoParity, EvenParity, OddParity, MarkParity, SpaceParity }EFI_PARITY_TYPE;
typedef enum{ DefaultStopBits, OneStopBit, OneFiveStopBits, TwoStopBits }EFI_STOP_BITS_TYPE;

//十二章八部三節一に記載せらるEFI_SERIAL_IO_PROTOCOL.Reset()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERIAL_RESET)( IN EFI_SERIAL_IO_PROTOCOL *This );

//十二章八部三節二に記載せらるEFI_SERIAL_IO_PROTOCOL.SetAttributes()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERIAL_SET_ATTRIBUTES)( IN EFI_SERIAL_IO_PROTOCOL *This, IN UINT64 BaudRate, IN UINT32 ReceiveFifoDepth, IN UINT32 Timeout, IN EFI_PARITY_TYPE Parity, IN UINT8 DataBits, IN EFI_STOP_BITS_TYPE StopBits );

//十二章八部三節三に記載せらるEFI_SERIAL_IO_PROTOCOL.SetControl()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERIAL_SET_CONTROL_BITS)( IN EFI_SERIAL_IO_PROTOCOL *This, IN UINT32 Control );
#define EFI_SERIAL_CLEAR_TO_SEND 0x0010
#define EFI_SERIAL_DATA_SET_READY 0x0020
#define EFI_SERIAL_RING_INDICATE 0x0040
#define EFI_SERIAL_CARRIER_DETECT 0x0080
#define EFI_SERIAL_REQUEST_TO_SEND 0x0002
#define EFI_SERIAL_DATA_TERMINAL_READY 0x0001
#define EFI_SERIAL_INPUT_BUFFER_EMPTY 0x0100
#define EFI_SERIAL_OUTPUT_BUFFER_EMPTY 0x0200
#define EFI_SERIAL_HARDWARE_LOOPBACK_ENABLE 0x1000
#define EFI_SERIAL_SOFTWARE_LOOPBACK_ENABLE 0x2000
#define EFI_SERIAL_HARDWARE_FLOW_CONTROL_ENABLE 0x4000

//十二章八部三節四に記載せらるEFI_SERIAL_IO_PROTOCOL.GetControl()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERIAL_GET_CONTROL_BITS)( IN EFI_SERIAL_IO_PROTOCOL *This, OUT UINT32 *Control );

//十二章八部三節五に記載せらるEFI_SERIAL_IO_PROTOCOL.Write()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERIAL_WRITE)( IN EFI_SERIAL_IO_PROTOCOL *This, IN OUT UINTN *BufferSize, IN VOID *Buffer );

//十二章八部三節六に記載せらるEFI_SERIAL_IO_PROTOCOL.Read()の定義
typedef EFI_STATUS (EFIAPI *EFI_SERIAL_READ)( IN EFI_SERIAL_IO_PROTOCOL *This, IN OUT UINTN *BufferSize, OUT VOID *Buffer );

//十二章九部二節に記載せらるEFI_GRAPHICS_OUTPUT_PROTOCOLの定義
#define EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID {0x9042a9de,0x23dc,0x4a38,{0x96,0xfb,0x7a,0xde,0xd0,0x80,0x51,0x6a}}
typedef EFI_GRAPHICS_OUTPUT_PROTOCOL_QUERY_MODE EFI_GRAPHICS_OUTPUT_PROTOCOL_QUERY_MODE;
typedef EFI_GRAPHICS_OUTPUT_PROTOCOL_SET_MODE EFI_GRAPHICS_OUTPUT_PROTOCOL_SET_MODE;
typedef EFI_GRAPHICS_OUTPUT_PROTOCOL_BLT EFI_GRAPHICS_OUTPUT_PROTOCOL_BLT;
typedef EFI_GRAPHICS_OUTPUT_PROTOCOL_MODE EFI_GRAPHICS_OUTPUT_PROTOCOL_MODE;
typedef struct EFI_GRAPHICS_OUTPUT_PROTCOL{ EFI_GRAPHICS_OUTPUT_PROTOCOL_QUERY_MODE QueryMode; EFI_GRAPHICS_OUTPUT_PROTOCOL_SET_MODE SetMode; EFI_GRAPHICS_OUTPUT_PROTOCOL_BLT Blt; EFI_GRAPHICS_OUTPUT_PROTOCOL_MODE *Mode; }EFI_GRAPHICS_OUTPUT_PROTOCOL;
typedef struct{ UINT32 RedMask; UINT32 GreenMask; UINT32 BlueMask; UINT32 ReservedMask; }EFI_PIXEL_BITMASK;
typedef EFI_GRAPHICS_PIXEL_FORMAT EFI_GRAPHICS_PIXEL_FORMAT;
typedef enum{ PixelRedGreenBlueReserved8BitPerColor, PixelBlueGreenRedReserved8BitPerColor, PixelBitMask, PixelBltOnly, PixelFormatMax }EFI_GRAPHICS_PIXEL_FORMAT;
typedef struct{ UINT32 Version; UINT32 HorizontalResolution; UINT32 VerticalResolution; EFI_GRAPHICS_PIXEL_FORMAT PixelFormat; EFI_PIXEL_BITMASK PixelInformation; UINT32 PixelsPerScanLine; }EFI_GRAPHICS_OUTPUT_MODE_INFORMATION;
typedef struct{ UINT32 MaxMode; UINT32 Mode; EFI_GRAPHICS_OUTPUT_MODE_INFORMATION *Info; UINTN SizeOfInfo; EFI_PHYSICAL_ADDRESS FrameBufferBase; UINTN FrameBufferSize; }EFI_GRAPHICS_OUTPUT_PROTOCOL_MODE;

//十二章九部二節一に記載せらるEFI_GRAPHICS_OUTPUT_PROTOCOL.QueryMode()の定義
typedef EFI_STATUS (EFIAPI *EFI_GRAPHICS_OUTPUT_PROTOCOL_QUERY_MODE)( IN EFI_GRAPHICS_OUTPUT_PROTOCOL *This, IN UINT32 ModeNumber, OUT UINTN *SizeOfInfo, OUT EFI_GRAPHICS_OUTPUT_MODE_INFORMATION **Info );

//十二章九部二節二に記載せらるEFI_GRAPHICS_OUTPUT_PROTOCOL.SetMode()の定義
typedef EFI_STATUS (EFIAPI *EFI_GRAPHICS_OUTPUT_PROTOCOL_SET_MODE)( IN EFI_GRAPHICS_OUTPUT_PROTOCOL *This, IN UINT32 ModeNumber );

//十二章九部二節三に記載せらるEFI_GRAPHICS_OUTPUT_PROTOCOL.Blt()の定義
typedef EFI_GRAPHICS_OUTPUT_BLT_PIXEL EFI_GRAPHICS_OUTPUT_BLT_PIXEL;
typedef EFI_GRAPHICS_OUTPUT_BLT_OPERATION EFI_GRAPHICS_OUTPUT_BLT_OPERATION;
typedef struct{ UINT8 Blue; UINT8 Green; UINT8 Red; UINT8 Reserved; }EFI_GRAPHICS_OUTPUT_BLT_PIXEL;
typedef enum{ EfiBltVideoFill, EfiBltVideoToBltBuffer, EfiBltBufferToVideo, EfiBltVideoToVideo, EfiGraphicsOutputBltOperationMax }EFI_GRAPHICS_OUTPUT_BLT_OPERATION;
typedef EFI_STATUS (EFIAPI *EFI_GRAPHICS_OUTPUT_PROTOCOL_BLT)( IN EFI_GRAPHICS_OUTPUT_PROTOCOL *This, IN OUT EFI_GRAPHICS_OUTPUT_BLT_PIXEL *BltBuffer OPTIONAL, IN EFI_GRAPHICS_OUTPUT_BLT_OPERATION BltOperation, IN UINTN SourceX, IN UINTN SourceY, IN UINTN DestinationX, IN UINTN DestinationY, IN UINTN Width, IN UINTN Height, IN UINTN Delta OPTIONAL );

//十二章九部二節四に記載せらるEFI_EDID_DISCOVERED_PROTOCOLの定義
#define EFI_EDID_DISCOVERED_PROTOCOL_GUID {0x1c0c34f6,0xd380,0x41fa,{0xa0,0x49,0x8a,0xd0,0x6c,0x1a,0x66,0xaa}}
typedef struct{ UINT32 SizeOfEdid; UINT8 *Edid; }EFI_EDID_DISCOVERED_PROTOCOL;

//十二章九部二節五に記載せらるEFI_EDID_ACTIVE_PROTOCOLの定義
#define EFI_EDID_ACTIVE_PROTOCOL_GUID {0xbd8c1056,0x9f36,0x44ec,{0x92,0xa8,0xa6,0x33,0x7f,0x81,0x79,0x86}}
typedef struct{ UINT32 SizeOfEdid; UINT8 *Edid; }EFI_EDID_ACTIVE_PROTOCOL;

//十二章九部二節六に記載せらるEFI_EDID_OVERRIDE_PROTOCOLの定義
#define EFI_EDID_OVERRIDE_PROTOCOL_GUID {0x48ecb431,0xfb72,0x45c0,{0xa9,0x22,0xf4,0x58,0xfe,0x04,0x0b,0xd5}}
typedef EFI_EDID_OVERRIDE_PROTOCOL_GET_EDID EFI_EDID_OVERRIDE_PROTOCOL_GET_EDID;
typedef struct _EFI_EDID_OVERRIDE_PROTOCOL{ EFI_EDID_OVERRIDE_PROTOCOL_GET_EDID GetEdid; }EFI_EDID_OVERRIDE_PROTOCOL;

//十二章九部二節七に記載せらるEFI_EDID_OVERRIDE_PROTOCOL.GetEdid()の定義
typedef EFI_STATUS (EFIAPI *EFI_EDID_OVERRIDE_PROTOCOL_GET_EDID)( IN EFI_EDID_OVERRIDE_PROTOCOL *This, IN EFI_HANDLE *ChildHandle, OUT UINT32 *Attributes, OUT UINTN *EdidSize, OUT UINT8 **Edid );
#define EFI_EDID_OVERRIDE_DONT_OVERRIDE 0x01
#define EFI_EDID_OVERRIDE_ENABLE_HOT_PLUG 0x02

#endif